
package presentacion;

import entidades.usuario;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logicaNegocio.TextPrompt;
import logicaNegocio.consultaUsuario;

public class ActualizarUsuario1 extends javax.swing.JFrame {


    public ActualizarUsuario1() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt jtUserID = new TextPrompt("Ingrese el ID del Usuario", jtActualizacion1IdUsuario);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpActualizacion1P1 = new javax.swing.JPanel();
        jlActualizacion1Logo = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlActualizacion1icon = new javax.swing.JLabel();
        jlCrearUsuario1 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpActualizacion1P2 = new javax.swing.JPanel();
        jlActualizacion1Exit = new javax.swing.JLabel();
        jlIDRegistro = new javax.swing.JLabel();
        jtActualizacion1IdUsuario = new javax.swing.JTextField();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jlActualizacion1Logout = new javax.swing.JLabel();
        jlActualizacion1BotonNext = new javax.swing.JLabel();
        jseparadorLogin = new javax.swing.JSeparator();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jlActualizacionMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpActualizacion1P1.setBackground(new java.awt.Color(0, 0, 0));
        jpActualizacion1P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlActualizacion1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jpActualizacion1P1.add(jlActualizacion1Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jpActualizacion1P1.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlActualizacion1icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-registration-90.png"))); // NOI18N
        jpActualizacion1P1.add(jlActualizacion1icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, 90));

        jlCrearUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario1.setText("Actualizar Datos");
        jpActualizacion1P1.add(jlCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jpActualizacion1P1.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jpActualizacion1P1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jpActualizacion1P2.setBackground(new java.awt.Color(51, 51, 51));
        jpActualizacion1P2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlActualizacion1Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlActualizacion1Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlActualizacion1Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlActualizacion1ExitMouseMoved(evt);
            }
        });
        jlActualizacion1Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlActualizacion1ExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlActualizacion1ExitMouseExited(evt);
            }
        });
        jpActualizacion1P2.add(jlActualizacion1Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlIDRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_ID.png"))); // NOI18N
        jpActualizacion1P2.add(jlIDRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jtActualizacion1IdUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jtActualizacion1IdUsuario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtActualizacion1IdUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtActualizacion1IdUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpActualizacion1P2.add(jtActualizacion1IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 320, 30));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpActualizacion1P2.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlActualizacion1Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlActualizacion1Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlActualizacion1Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlActualizacion1LogoutMouseMoved(evt);
            }
        });
        jlActualizacion1Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlActualizacion1LogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlActualizacion1LogoutMouseExited(evt);
            }
        });
        jpActualizacion1P2.add(jlActualizacion1Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlActualizacion1BotonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ok-90.png"))); // NOI18N
        jlActualizacion1BotonNext.setText("jLabel1");
        jlActualizacion1BotonNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlActualizacion1BotonNext.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlActualizacion1BotonNextMouseMoved(evt);
            }
        });
        jlActualizacion1BotonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlActualizacion1BotonNextMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlActualizacion1BotonNextMouseExited(evt);
            }
        });
        jpActualizacion1P2.add(jlActualizacion1BotonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 80));

        jseparadorLogin.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpActualizacion1P2.add(jseparadorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jpActualizacion1P2.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jpActualizacion1P2.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jpActualizacion1P2.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jlActualizacionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlActualizacionMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlActualizacionMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlActualizacionMenuMouseMoved(evt);
            }
        });
        jlActualizacionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlActualizacionMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlActualizacionMenuMouseExited(evt);
            }
        });
        jpActualizacion1P2.add(jlActualizacionMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpActualizacion1P1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jpActualizacion1P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpActualizacion1P1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpActualizacion1P2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;
    
    //Metodo para recibir desde login los siguientes parametros para distintos usos, esta en todos los frames
    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));
    
    private void jlActualizacion1ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1ExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlActualizacion1ExitMouseClicked

    private void jlActualizacion1BotonNextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1BotonNextMouseMoved
        jlActualizacion1BotonNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlActualizacion1BotonNextMouseMoved

    private void jlActualizacion1BotonNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1BotonNextMouseExited
        jlActualizacion1BotonNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlActualizacion1BotonNextMouseExited

    private void jlActualizacion1ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1ExitMouseMoved
        jlActualizacion1Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlActualizacion1ExitMouseMoved

    private void jlActualizacion1ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1ExitMouseExited
        jlActualizacion1Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlActualizacion1ExitMouseExited

    private void jlActualizacion1LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1LogoutMouseMoved
        jlActualizacion1Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlActualizacion1LogoutMouseMoved

    private void jlActualizacion1LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1LogoutMouseExited
        jlActualizacion1Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlActualizacion1LogoutMouseExited

    private void jlActualizacionMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacionMenuMouseMoved
        jlActualizacionMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlActualizacionMenuMouseMoved

    private void jlActualizacionMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacionMenuMouseExited
        jlActualizacionMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlActualizacionMenuMouseExited

    // metodo para revisar si el usuario ingresado existe en el sistema y para evitar que usuario intente actualizar otro usuario
    public void consultaUsuario() {

        consultaUsuario u1 = new consultaUsuario();

        ArrayList<usuario> usuario;

        boolean usuarioEncontrado = false;

        usuario = u1.reporteUsuario();

        if (usuario != null) {

            if (jtActualizacion1IdUsuario.getText().equals(userId)) {
                usuarioEncontrado = true;
                actualizarUsuario2 au2 = new actualizarUsuario2();
                au2.LlenadoCampos(jtActualizacion1IdUsuario.getText());
                au2.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
                au2.setVisible(true);
                this.setVisible(false);
            } else {
                usuarioEncontrado = false;
            }
            if (usuarioEncontrado == false) {
                JOptionPane.showMessageDialog(null, "No puede actualizar otros usuarios","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                jtActualizacion1IdUsuario.setText("");
            }

        }

    }
    private void jlActualizacion1BotonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1BotonNextMouseClicked
        if (jtActualizacion1IdUsuario.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese el ID del Usuario","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
        } else {
            consultaUsuario();
        }
    }//GEN-LAST:event_jlActualizacion1BotonNextMouseClicked

    private void jlActualizacion1LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacion1LogoutMouseClicked
        Login l20 = new Login();
        l20.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jlActualizacion1LogoutMouseClicked

    private void jlActualizacionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlActualizacionMenuMouseClicked
        menuOpcionesUser r1 = new menuOpcionesUser();
        r1.setVisible(true);
        this.setVisible(false);
        r1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
    }//GEN-LAST:event_jlActualizacionMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarUsuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarUsuario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlActualizacion1BotonNext;
    private javax.swing.JLabel jlActualizacion1Exit;
    private javax.swing.JLabel jlActualizacion1Logo;
    private javax.swing.JLabel jlActualizacion1Logout;
    private javax.swing.JLabel jlActualizacion1icon;
    private javax.swing.JLabel jlActualizacionMenu;
    private javax.swing.JLabel jlCrearUsuario1;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlIDRegistro;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JPanel jpActualizacion1P1;
    private javax.swing.JPanel jpActualizacion1P2;
    private javax.swing.JSeparator jseparadorLogin;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JTextField jtActualizacion1IdUsuario;
    // End of variables declaration//GEN-END:variables
}
