package presentacion;

import entidades.canciones;
import entidades.generosMusicales;
import java.awt.List;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logicaNegocio.TextPrompt;
import logicaNegocio.cancionesVarios;
import logicaNegocio.generosMusicalesVarios;

/**
 *
 * @author obarboza
 */
public class cancionesActualizar extends javax.swing.JFrame {

    /**
     * Creates new form cancionesActualizar
     */
    public cancionesActualizar() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt jtNombreCancionget = new TextPrompt("Nombre de la Cancion Seleccionada", jtCancionesActualizarGetNombreCancion);
        TextPrompt jtPrecioCancionget = new TextPrompt("Precio de la Cancion Seleccionada", jtCancionesActualizarGetPrecioCancion1);
        TextPrompt jtNombreCancion = new TextPrompt("Ingrese el Nombre de la Cancion", jtCancionesActualizarSetNombreCancion);
        TextPrompt jtPrecioCancion = new TextPrompt("Ingrese el Precio de la Cancion", jtCancionesActualizarSetPrecioCancion);
        TextPrompt jtGeneroCancion = new TextPrompt("Genero de la cancion seleccionada", jtCancionesActualizarGetCodigoGenero);
        TextPrompt jtDescGeneroCancion = new TextPrompt("Descripcion del Genero", jtCancionesActualizarGetDescGenero);
        cargarComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCancionesActualizar1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlNextRegistro = new javax.swing.JLabel();
        jseparadorLogin5 = new javax.swing.JSeparator();
        jlCrearUsuario5 = new javax.swing.JLabel();
        jlCancionesActualizarBotonActualizar = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpCancionesActualizar2 = new javax.swing.JPanel();
        jlCancionesActualizarExit = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlCancionesActualizarLogout = new javax.swing.JLabel();
        jlCancionesActualizarMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlNombreRegistro = new javax.swing.JLabel();
        jlGeneroRegistro = new javax.swing.JLabel();
        jtCancionesActualizarSetNombreCancion = new javax.swing.JTextField();
        jtCancionesActualizarSetPrecioCancion = new javax.swing.JTextField();
        jlGeneroRegistro1 = new javax.swing.JLabel();
        jlCrearUsuario8 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jcCancionesActualizarCanciones = new javax.swing.JComboBox<>();
        jlGeneroRegistro2 = new javax.swing.JLabel();
        jtCancionesActualizarGetNombreCancion = new javax.swing.JTextField();
        jlGeneroRegistro3 = new javax.swing.JLabel();
        jtCancionesActualizarGetPrecioCancion1 = new javax.swing.JTextField();
        jtCancionesActualizarGetCodigoGenero = new javax.swing.JTextField();
        jlGeneroRegistro4 = new javax.swing.JLabel();
        jlNombreRegistro1 = new javax.swing.JLabel();
        jcCancionesActualizarGenero = new javax.swing.JComboBox<>();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jtCancionesActualizarGetDescGenero = new javax.swing.JTextField();
        jlGeneroRegistro5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpCancionesActualizar1.setBackground(new java.awt.Color(0, 0, 0));
        jpCancionesActualizar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jpCancionesActualizar1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-music-folder-60.png"))); // NOI18N
        jpCancionesActualizar1.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 60, 60));

        jseparadorLogin5.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin5.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpCancionesActualizar1.add(jseparadorLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 10, 50));

        jlCrearUsuario5.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario5.setText("Canciones");
        jpCancionesActualizar1.add(jlCrearUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlCancionesActualizarBotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-update-60.png"))); // NOI18N
        jlCancionesActualizarBotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesActualizarBotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarBotonActualizarMouseMoved(evt);
            }
        });
        jlCancionesActualizarBotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarBotonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarBotonActualizarMouseExited(evt);
            }
        });
        jpCancionesActualizar1.add(jlCancionesActualizarBotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 70, 70));

        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Actualizar ");
        jpCancionesActualizar1.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jpCancionesActualizar1.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jpCancionesActualizar1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jpCancionesActualizar2.setBackground(new java.awt.Color(51, 51, 51));
        jpCancionesActualizar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCancionesActualizarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlCancionesActualizarExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesActualizarExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarExitMouseMoved(evt);
            }
        });
        jlCancionesActualizarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarExitMouseExited(evt);
            }
        });
        jpCancionesActualizar2.add(jlCancionesActualizarExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpCancionesActualizar2.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlCancionesActualizarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlCancionesActualizarLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesActualizarLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarLogoutMouseMoved(evt);
            }
        });
        jlCancionesActualizarLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarLogoutMouseExited(evt);
            }
        });
        jpCancionesActualizar2.add(jlCancionesActualizarLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCancionesActualizarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlCancionesActualizarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesActualizarMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarMenuMouseMoved(evt);
            }
        });
        jlCancionesActualizarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesActualizarMenuMouseExited(evt);
            }
        });
        jpCancionesActualizar2.add(jlCancionesActualizarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpCancionesActualizar2.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlNombreRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlGeneroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jtCancionesActualizarSetNombreCancion.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarSetNombreCancion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarSetNombreCancion.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarSetNombreCancion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarSetNombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 320, 30));

        jtCancionesActualizarSetPrecioCancion.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarSetPrecioCancion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarSetPrecioCancion.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarSetPrecioCancion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarSetPrecioCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 320, 30));

        jlGeneroRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-money-bag-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jlCrearUsuario8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario8.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario8.setText("Menu");
        jpCancionesActualizar2.add(jlCrearUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jpCancionesActualizar2.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jpCancionesActualizar2.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jcCancionesActualizarCanciones.setBackground(new java.awt.Color(0, 0, 0));
        jcCancionesActualizarCanciones.setForeground(new java.awt.Color(102, 102, 102));
        jcCancionesActualizarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCancionesActualizarCancionesActionPerformed(evt);
            }
        });
        jpCancionesActualizar2.add(jcCancionesActualizarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 320, 30));

        jlGeneroRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jtCancionesActualizarGetNombreCancion.setEditable(false);
        jtCancionesActualizarGetNombreCancion.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarGetNombreCancion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarGetNombreCancion.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarGetNombreCancion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarGetNombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 30));

        jlGeneroRegistro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-money-bag-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jtCancionesActualizarGetPrecioCancion1.setEditable(false);
        jtCancionesActualizarGetPrecioCancion1.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarGetPrecioCancion1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarGetPrecioCancion1.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarGetPrecioCancion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarGetPrecioCancion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 320, 30));

        jtCancionesActualizarGetCodigoGenero.setEditable(false);
        jtCancionesActualizarGetCodigoGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarGetCodigoGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarGetCodigoGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarGetCodigoGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarGetCodigoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 320, 30));

        jlGeneroRegistro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jlNombreRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-qr-code-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlNombreRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jcCancionesActualizarGenero.setBackground(new java.awt.Color(0, 0, 0));
        jcCancionesActualizarGenero.setForeground(new java.awt.Color(102, 102, 102));
        jpCancionesActualizar2.add(jcCancionesActualizarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 320, 30));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jpCancionesActualizar2.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 340, 10));

        jtCancionesActualizarGetDescGenero.setEditable(false);
        jtCancionesActualizarGetDescGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtCancionesActualizarGetDescGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtCancionesActualizarGetDescGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtCancionesActualizarGetDescGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCancionesActualizar2.add(jtCancionesActualizarGetDescGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 320, 30));

        jlGeneroRegistro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-qr-code-30.png"))); // NOI18N
        jpCancionesActualizar2.add(jlGeneroRegistro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpCancionesActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jpCancionesActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpCancionesActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpCancionesActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));

    public void cargarComboBox() {

        cancionesVarios c1 = new cancionesVarios();

        ArrayList<canciones> cancionesDetalles;

        cancionesDetalles = c1.actualizarCancionesToCombo();

        generosMusicalesVarios gmv = new generosMusicalesVarios();
        ArrayList<generosMusicales> generosMusicales;

        generosMusicales = gmv.actualizarGeneroToCombo();

        if (cancionesDetalles != null) {

            jcCancionesActualizarCanciones.addItem("Seleccione Codigo de Cancion");

            for (int i = 0; i < cancionesDetalles.size(); i++) {
                jcCancionesActualizarCanciones.addItem(cancionesDetalles.get(i).getCodigoCancion());
            }
        }

        if (generosMusicales != null) {

            jcCancionesActualizarGenero.addItem("Seleccione Codigo de Genero");

            for (int i = 0; i < generosMusicales.size(); i++) {
                jcCancionesActualizarGenero.addItem(generosMusicales.get(i).getCodigoGenero());
            }
        }

    }

    public void llenadoCamposTexto() {
        String nombreCancion = "";
        Double precioCancion = 0.0;
        String codigoGenero = "";
        String descGenero = "";

        cancionesVarios c1 = new cancionesVarios();

        ArrayList<canciones> canciones;

        canciones = c1.actualizarCancionesToCombo();

        if (jcCancionesActualizarCanciones.getSelectedIndex() == 0) {
            jtCancionesActualizarGetNombreCancion.setText("");
            jtCancionesActualizarGetCodigoGenero.setText("");
            jtCancionesActualizarGetPrecioCancion1.setText("");
            jtCancionesActualizarGetDescGenero.setText("");
        }
        for (int i = 0; i < canciones.size(); i++) {

            if (canciones.get(i).getCodigoCancion().equals(jcCancionesActualizarCanciones.getSelectedItem())) {
                nombreCancion = canciones.get(i).getNombreCancion();
                precioCancion = canciones.get(i).getPrecioCancion();
                codigoGenero = canciones.get(i).getCodigoGeneroCancion();
                descGenero = canciones.get(i).getDescripcionGeneroCancion();
                jtCancionesActualizarGetNombreCancion.setText(nombreCancion);
                jtCancionesActualizarGetCodigoGenero.setText(codigoGenero);
                jtCancionesActualizarGetDescGenero.setText(descGenero);
                jtCancionesActualizarGetPrecioCancion1.setText(String.valueOf(precioCancion));
            }
        }

    }

    private void jlCancionesActualizarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlCancionesActualizarExitMouseClicked

    private void jlCancionesActualizarExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarExitMouseMoved
        jlCancionesActualizarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesActualizarExitMouseMoved

    private void jlCancionesActualizarExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarExitMouseExited
        jlCancionesActualizarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesActualizarExitMouseExited

    private void jlCancionesActualizarLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarLogoutMouseMoved
        jlCancionesActualizarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesActualizarLogoutMouseMoved

    private void jlCancionesActualizarLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarLogoutMouseExited
        jlCancionesActualizarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesActualizarLogoutMouseExited

    private void jlCancionesActualizarMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarMenuMouseMoved
        jlCancionesActualizarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesActualizarMenuMouseMoved

    private void jlCancionesActualizarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarMenuMouseExited
        jlCancionesActualizarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesActualizarMenuMouseExited

    private void jlCancionesActualizarBotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarBotonActualizarMouseMoved
        jlCancionesActualizarBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesActualizarBotonActualizarMouseMoved

    private void jlCancionesActualizarBotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarBotonActualizarMouseExited
        jlCancionesActualizarBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesActualizarBotonActualizarMouseExited


    private void jlCancionesActualizarLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarLogoutMouseClicked
        Login l8 = new Login();
        l8.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesActualizarLogoutMouseClicked

    private void jlCancionesActualizarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarMenuMouseClicked
        cancionesMenu cm1 = new cancionesMenu();
        cm1.setVisible(true);
        cm1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesActualizarMenuMouseClicked

    private void jlCancionesActualizarBotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesActualizarBotonActualizarMouseClicked
        if (jcCancionesActualizarCanciones.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Seleccione un Codigo de Cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
        } else {
            if (jcCancionesActualizarGenero.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Por Favor Seleccione un Codigo de Genero", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
            } else {
                if (jtCancionesActualizarSetNombreCancion.getText().length() == 0) {
                    JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Nombre de la Cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                } else {
                    if (jtCancionesActualizarSetNombreCancion.getText().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Nombre de la Cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                    } else {
                        if (jtCancionesActualizarSetPrecioCancion.getText().length() == 0) {
                            JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Precio de la Cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                        } else {
                            canciones c1 = new canciones();
                            cancionesVarios cv = new cancionesVarios();

                            ArrayList<canciones> canciones;
                            canciones = cv.actualizarCancionesToCombo();

                            boolean cancionRepetida = false;

                            for (int i = 0; i < canciones.size(); i++) {

                                if (canciones.get(i).getNombreCancion().equals(jtCancionesActualizarSetNombreCancion.getText())) {
                                    cancionRepetida = true;
                                    break;
                                }
                            }

                            if (cancionRepetida == true) {
                                JOptionPane.showMessageDialog(null, "Cancion ya existe, favor intentar de nuevo", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                            } else {
                                c1.setCodigoCancion(jcCancionesActualizarCanciones.getSelectedItem().toString());
                                c1.setNombreCancion(jtCancionesActualizarSetNombreCancion.getText().toString());
                                c1.setCodigoGeneroCancion(jcCancionesActualizarGenero.getSelectedItem().toString());
                                c1.setPrecioCancion(Double.parseDouble(jtCancionesActualizarSetPrecioCancion.getText()));
                                JOptionPane.showMessageDialog(null, "Cancion actualizada correctamente", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                            }

                            if (cv.actualizarCancion(c1) == true) {                                
                                jtCancionesActualizarGetNombreCancion.setText("");
                                jtCancionesActualizarGetPrecioCancion1.setText("");
                                jtCancionesActualizarGetCodigoGenero.setText("");
                                jtCancionesActualizarSetNombreCancion.setText("");
                                jtCancionesActualizarSetPrecioCancion.setText("");
                                jtCancionesActualizarGetDescGenero.setText("");
                                jcCancionesActualizarCanciones.setSelectedItem("Seleccione Codigo de Cancion");
                                jcCancionesActualizarGenero.setSelectedItem("Seleccione Codigo de Genero");

                            } else {
                                JOptionPane.showMessageDialog(null, "Falló la actualizacion de la cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                                jtCancionesActualizarGetNombreCancion.setText("");
                                jtCancionesActualizarGetPrecioCancion1.setText("");
                                jtCancionesActualizarGetCodigoGenero.setText("");
                                jtCancionesActualizarSetNombreCancion.setText("");
                                jtCancionesActualizarSetPrecioCancion.setText("");
                                jtCancionesActualizarGetDescGenero.setText("");
                                jcCancionesActualizarCanciones.setSelectedItem("Seleccione Codigo de Cancion");
                                jcCancionesActualizarGenero.setSelectedItem("Seleccione Codigo de Genero");
                            }

                        }
                    }
                }

            }
        }
    }//GEN-LAST:event_jlCancionesActualizarBotonActualizarMouseClicked

    private void jcCancionesActualizarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCancionesActualizarCancionesActionPerformed
        llenadoCamposTexto();
    }//GEN-LAST:event_jcCancionesActualizarCancionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancionesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancionesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancionesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancionesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancionesActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcCancionesActualizarCanciones;
    private javax.swing.JComboBox<String> jcCancionesActualizarGenero;
    private javax.swing.JLabel jlCancionesActualizarBotonActualizar;
    private javax.swing.JLabel jlCancionesActualizarExit;
    private javax.swing.JLabel jlCancionesActualizarLogout;
    private javax.swing.JLabel jlCancionesActualizarMenu;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario5;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario8;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGeneroRegistro;
    private javax.swing.JLabel jlGeneroRegistro1;
    private javax.swing.JLabel jlGeneroRegistro2;
    private javax.swing.JLabel jlGeneroRegistro3;
    private javax.swing.JLabel jlGeneroRegistro4;
    private javax.swing.JLabel jlGeneroRegistro5;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlNombreRegistro;
    private javax.swing.JLabel jlNombreRegistro1;
    private javax.swing.JPanel jpCancionesActualizar1;
    private javax.swing.JPanel jpCancionesActualizar2;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin5;
    private javax.swing.JTextField jtCancionesActualizarGetCodigoGenero;
    private javax.swing.JTextField jtCancionesActualizarGetDescGenero;
    private javax.swing.JTextField jtCancionesActualizarGetNombreCancion;
    private javax.swing.JTextField jtCancionesActualizarGetPrecioCancion1;
    private javax.swing.JTextField jtCancionesActualizarSetNombreCancion;
    private javax.swing.JTextField jtCancionesActualizarSetPrecioCancion;
    // End of variables declaration//GEN-END:variables
}
