/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.canciones;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaNegocio.cancionesVarios;

/**
 *
 * @author obarboza
 */
public class cancionesConsultar extends javax.swing.JFrame {

    /**
     * Creates new form cancionesConsultar
     */
    public cancionesConsultar() {
        initComponents();
        setLocationRelativeTo(null);
        consultaCanciones();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jseparadorLogin5 = new javax.swing.JSeparator();
        jlCrearUsuario5 = new javax.swing.JLabel();
        jlNextRegistro2 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlCancionesConsultarExit = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlCancionesConsultarLogout = new javax.swing.JLabel();
        jlCancionesConsultarMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultaCanciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-library-60.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 60));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Consulta");
        jp1MenuRegistro.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jseparadorLogin5.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin5.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp1MenuRegistro.add(jseparadorLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 10, 50));

        jlCrearUsuario5.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario5.setText("Canciones");
        jp1MenuRegistro.add(jlCrearUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlNextRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-consultation-60.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 60));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCancionesConsultarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlCancionesConsultarExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesConsultarExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarExitMouseMoved(evt);
            }
        });
        jlCancionesConsultarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesConsultarExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlCancionesConsultarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlCancionesConsultarLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesConsultarLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarLogoutMouseMoved(evt);
            }
        });
        jlCancionesConsultarLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesConsultarLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCancionesConsultarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlCancionesConsultarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesConsultarMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarMenuMouseMoved(evt);
            }
        });
        jlCancionesConsultarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesConsultarMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesConsultarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jtConsultaCanciones.setBackground(new java.awt.Color(0, 0, 0));
        jtConsultaCanciones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtConsultaCanciones.setForeground(new java.awt.Color(135, 211, 124));
        jtConsultaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtConsultaCanciones.setToolTipText("");
        jtConsultaCanciones.setGridColor(new java.awt.Color(102, 102, 102));
        jtConsultaCanciones.setSelectionBackground(new java.awt.Color(135, 211, 124));
        jtConsultaCanciones.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jtConsultaCanciones);

        jp2MenuRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    public void consultaCanciones() {

        cancionesVarios cv = new cancionesVarios();

        ArrayList<canciones> canciones;

        canciones = cv.actualizarCancionesToCombo();

        if (canciones != null) {

            DefaultTableModel modelo = new DefaultTableModel();

            String[] nombresColumnas = {"Codigo Cancion", "Nombre Cancion", "Precio Cancion"};

            modelo.setColumnIdentifiers(nombresColumnas);

            Object[] columna = new Object[modelo.getColumnCount()];

            for (int i = 0; i < canciones.size(); i++) {

                columna[0] = canciones.get(i).getCodigoCancion();
                columna[1] = canciones.get(i).getNombreCancion();
                columna[2] = canciones.get(i).getPrecioCancion() + " Colones";

                modelo.addRow(columna);
            }

            jtConsultaCanciones.setModel(modelo);
        }
    }

    private void jlCancionesConsultarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlCancionesConsultarExitMouseClicked

    private void jlCancionesConsultarExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarExitMouseMoved

        jlCancionesConsultarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesConsultarExitMouseMoved

    private void jlCancionesConsultarExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarExitMouseExited
        jlCancionesConsultarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesConsultarExitMouseExited

    private void jlCancionesConsultarLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarLogoutMouseMoved
        jlCancionesConsultarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesConsultarLogoutMouseMoved

    private void jlCancionesConsultarLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarLogoutMouseExited
        jlCancionesConsultarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesConsultarLogoutMouseExited

    private void jlCancionesConsultarMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarMenuMouseMoved
        jlCancionesConsultarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesConsultarMenuMouseMoved

    private void jlCancionesConsultarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarMenuMouseExited
        jlCancionesConsultarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesConsultarMenuMouseExited

    private void jlCancionesConsultarLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarLogoutMouseClicked
        Login l9 = new Login();
        l9.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesConsultarLogoutMouseClicked

    private void jlCancionesConsultarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesConsultarMenuMouseClicked
        cancionesMenu cm5 = new cancionesMenu();
        cm5.setVisible(true);
        cm5.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesConsultarMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancionesConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancionesConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancionesConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancionesConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancionesConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCancionesConsultarExit;
    private javax.swing.JLabel jlCancionesConsultarLogout;
    private javax.swing.JLabel jlCancionesConsultarMenu;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario5;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNextRegistro2;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin5;
    private javax.swing.JTable jtConsultaCanciones;
    // End of variables declaration//GEN-END:variables
}
