/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author obarboza
 */
public class cancionesMenu extends javax.swing.JFrame {

    /**
     * Creates new form cancionesMenu
     */
    public cancionesMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlCancionesMenuExit = new javax.swing.JLabel();
        jlCancionesMenuBotonAgregarCanciones = new javax.swing.JLabel();
        jlCrearUsuario1 = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlCancionesMenuLogout = new javax.swing.JLabel();
        jlCrearUsuario2 = new javax.swing.JLabel();
        jlCancionesMenuBotonActualizarCanciones = new javax.swing.JLabel();
        jlCancionesMenuMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlCancionesMenuBotonConsultarCanciones = new javax.swing.JLabel();
        jlCrearUsuario4 = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-music-folder-90.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, 90));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Canciones");
        jp1MenuRegistro.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCancionesMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlCancionesMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuExitMouseMoved(evt);
            }
        });
        jlCancionesMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlCancionesMenuBotonAgregarCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-90.png"))); // NOI18N
        jlCancionesMenuBotonAgregarCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuBotonAgregarCanciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonAgregarCancionesMouseMoved(evt);
            }
        });
        jlCancionesMenuBotonAgregarCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonAgregarCancionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonAgregarCancionesMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuBotonAgregarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, 80));

        jlCrearUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario1.setText("Actualizar Canciones");
        jp2MenuRegistro.add(jlCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 10, 80));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlCancionesMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlCancionesMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuLogoutMouseMoved(evt);
            }
        });
        jlCancionesMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario2.setText("Agregar Canciones");
        jp2MenuRegistro.add(jlCrearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jlCancionesMenuBotonActualizarCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-update-left-rotation-90.png"))); // NOI18N
        jlCancionesMenuBotonActualizarCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuBotonActualizarCanciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonActualizarCancionesMouseMoved(evt);
            }
        });
        jlCancionesMenuBotonActualizarCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonActualizarCancionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonActualizarCancionesMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuBotonActualizarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 100, 90));

        jlCancionesMenuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlCancionesMenuMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuMenuMouseMoved(evt);
            }
        });
        jlCancionesMenuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlCancionesMenuBotonConsultarCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-consultation-90.png"))); // NOI18N
        jlCancionesMenuBotonConsultarCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCancionesMenuBotonConsultarCanciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonConsultarCancionesMouseMoved(evt);
            }
        });
        jlCancionesMenuBotonConsultarCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonConsultarCancionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCancionesMenuBotonConsultarCancionesMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlCancionesMenuBotonConsultarCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 90));

        jlCrearUsuario4.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario4.setText("Consultar Canciones");
        jp2MenuRegistro.add(jlCrearUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    private void jlCancionesMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlCancionesMenuExitMouseClicked

    private void jlCancionesMenuExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuExitMouseMoved
        jlCancionesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuExitMouseMoved

    private void jlCancionesMenuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuExitMouseExited
        jlCancionesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuExitMouseExited

    private void jlCancionesMenuLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuLogoutMouseMoved
        jlCancionesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuLogoutMouseMoved

    private void jlCancionesMenuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuLogoutMouseExited
        jlCancionesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuLogoutMouseExited

    private void jlCancionesMenuMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuMenuMouseMoved
        jlCancionesMenuMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuMenuMouseMoved

    private void jlCancionesMenuMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuMenuMouseExited
        jlCancionesMenuMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuMenuMouseExited

    private void jlCancionesMenuBotonAgregarCancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonAgregarCancionesMouseMoved
        jlCancionesMenuBotonAgregarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuBotonAgregarCancionesMouseMoved

    private void jlCancionesMenuBotonAgregarCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonAgregarCancionesMouseExited
        jlCancionesMenuBotonAgregarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuBotonAgregarCancionesMouseExited

    private void jlCancionesMenuBotonActualizarCancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonActualizarCancionesMouseMoved
        jlCancionesMenuBotonActualizarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuBotonActualizarCancionesMouseMoved

    private void jlCancionesMenuBotonActualizarCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonActualizarCancionesMouseExited
        jlCancionesMenuBotonActualizarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuBotonActualizarCancionesMouseExited

    private void jlCancionesMenuBotonConsultarCancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonConsultarCancionesMouseMoved
        jlCancionesMenuBotonConsultarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlCancionesMenuBotonConsultarCancionesMouseMoved

    private void jlCancionesMenuBotonConsultarCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonConsultarCancionesMouseExited
        jlCancionesMenuBotonConsultarCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlCancionesMenuBotonConsultarCancionesMouseExited

    private void jlCancionesMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuLogoutMouseClicked
        Login l7 = new Login();
        l7.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesMenuLogoutMouseClicked

    private void jlCancionesMenuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuMenuMouseClicked
        menuOpcionesAdmin moa3 = new menuOpcionesAdmin();
        moa3.setVisible(true);
        moa3.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesMenuMenuMouseClicked

    private void jlCancionesMenuBotonAgregarCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonAgregarCancionesMouseClicked
        CancionesAgregar ca1 = new CancionesAgregar();
        ca1.setVisible(true);
        ca1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);

    }//GEN-LAST:event_jlCancionesMenuBotonAgregarCancionesMouseClicked

    private void jlCancionesMenuBotonActualizarCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonActualizarCancionesMouseClicked
        cancionesActualizar ca2 = new cancionesActualizar();
        ca2.setVisible(true);
        ca2.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesMenuBotonActualizarCancionesMouseClicked

    private void jlCancionesMenuBotonConsultarCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCancionesMenuBotonConsultarCancionesMouseClicked
        cancionesConsultar cc1 = new cancionesConsultar();
        cc1.setVisible(true);
        cc1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlCancionesMenuBotonConsultarCancionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancionesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlCancionesMenuBotonActualizarCanciones;
    private javax.swing.JLabel jlCancionesMenuBotonAgregarCanciones;
    private javax.swing.JLabel jlCancionesMenuBotonConsultarCanciones;
    private javax.swing.JLabel jlCancionesMenuExit;
    private javax.swing.JLabel jlCancionesMenuLogout;
    private javax.swing.JLabel jlCancionesMenuMenu;
    private javax.swing.JLabel jlCrearUsuario1;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario2;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario4;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    // End of variables declaration//GEN-END:variables
}
