/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import accesoDatos.accDat;
import entidades.canciones;
import entidades.generosMusicales;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logicaNegocio.TextPrompt;
import logicaNegocio.cancionesVarios;
import logicaNegocio.generosMusicalesVarios;

/**
 *
 * @author obarboza
 */
public class generosMusicalesActualizar extends javax.swing.JFrame {

    /**
     * Creates new form generosMusicalesActualizar
     */
    public generosMusicalesActualizar() {
        initComponents();
        setLocationRelativeTo(null);

        TextPrompt jtDescripcionGeneroget = new TextPrompt("Descripcion Actual del Genero", jtGenerosMusicalesActualizarGetDescGenero);
        TextPrompt jtDescripcionGeneroset = new TextPrompt("Ingrese la descripcion del Genero", jtGenerosMusicalesActualizarSetDescGenero);
        cargarComboBox();
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGenerosMusicalesActualizar1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jseparadorLogin5 = new javax.swing.JSeparator();
        jlCrearUsuario5 = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlNextRegistro2 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpGenerosMusicalesActualizar2 = new javax.swing.JPanel();
        jlGenerosMusicalesActualizarExit = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlGenerosMusicalesActualizarLogout = new javax.swing.JLabel();
        jlGenerosMusicalesActualizarMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlNombreRegistro = new javax.swing.JLabel();
        jlGeneroRegistro = new javax.swing.JLabel();
        jtGenerosMusicalesActualizarSetDescGenero = new javax.swing.JTextField();
        jlGenerosMusicalesActualizarBotonActualizar = new javax.swing.JLabel();
        jlCrearUsuario7 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jlCrearUsuario12 = new javax.swing.JLabel();
        jcGenerosMusicalesActualizarGetCodigoGenero = new javax.swing.JComboBox<>();
        jlGeneroRegistro1 = new javax.swing.JLabel();
        jtGenerosMusicalesActualizarGetDescGenero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpGenerosMusicalesActualizar1.setBackground(new java.awt.Color(0, 0, 0));
        jpGenerosMusicalesActualizar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jpGenerosMusicalesActualizar1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jpGenerosMusicalesActualizar1.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-60.png"))); // NOI18N
        jpGenerosMusicalesActualizar1.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 60));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Actualizar");
        jpGenerosMusicalesActualizar1.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jseparadorLogin5.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin5.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpGenerosMusicalesActualizar1.add(jseparadorLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 10, 50));

        jlCrearUsuario5.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario5.setText("Generos");
        jpGenerosMusicalesActualizar1.add(jlCrearUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Generos");
        jpGenerosMusicalesActualizar1.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlNextRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-update-left-rotation-60.png"))); // NOI18N
        jpGenerosMusicalesActualizar1.add(jlNextRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 60));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jpGenerosMusicalesActualizar1.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jpGenerosMusicalesActualizar1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jpGenerosMusicalesActualizar2.setBackground(new java.awt.Color(51, 51, 51));
        jpGenerosMusicalesActualizar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGenerosMusicalesActualizarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlGenerosMusicalesActualizarExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesActualizarExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarExitMouseMoved(evt);
            }
        });
        jlGenerosMusicalesActualizarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarExitMouseExited(evt);
            }
        });
        jpGenerosMusicalesActualizar2.add(jlGenerosMusicalesActualizarExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpGenerosMusicalesActualizar2.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlGenerosMusicalesActualizarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlGenerosMusicalesActualizarLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesActualizarLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarLogoutMouseMoved(evt);
            }
        });
        jlGenerosMusicalesActualizarLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarLogoutMouseExited(evt);
            }
        });
        jpGenerosMusicalesActualizar2.add(jlGenerosMusicalesActualizarLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlGenerosMusicalesActualizarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlGenerosMusicalesActualizarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesActualizarMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarMenuMouseMoved(evt);
            }
        });
        jlGenerosMusicalesActualizarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarMenuMouseExited(evt);
            }
        });
        jpGenerosMusicalesActualizar2.add(jlGenerosMusicalesActualizarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jpGenerosMusicalesActualizar2.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlNombreRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-qr-code-30.png"))); // NOI18N
        jpGenerosMusicalesActualizar2.add(jlNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jlGeneroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jpGenerosMusicalesActualizar2.add(jlGeneroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jtGenerosMusicalesActualizarSetDescGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtGenerosMusicalesActualizarSetDescGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtGenerosMusicalesActualizarSetDescGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtGenerosMusicalesActualizarSetDescGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpGenerosMusicalesActualizar2.add(jtGenerosMusicalesActualizarSetDescGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 320, 30));

        jlGenerosMusicalesActualizarBotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-update-90.png"))); // NOI18N
        jlGenerosMusicalesActualizarBotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesActualizarBotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarBotonActualizarMouseMoved(evt);
            }
        });
        jlGenerosMusicalesActualizarBotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarBotonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesActualizarBotonActualizarMouseExited(evt);
            }
        });
        jpGenerosMusicalesActualizar2.add(jlGenerosMusicalesActualizarBotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jlCrearUsuario7.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario7.setText("Actualizar Genero");
        jpGenerosMusicalesActualizar2.add(jlCrearUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jpGenerosMusicalesActualizar2.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jpGenerosMusicalesActualizar2.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jlCrearUsuario12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario12.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario12.setText("Menu");
        jpGenerosMusicalesActualizar2.add(jlCrearUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jcGenerosMusicalesActualizarGetCodigoGenero.setBackground(new java.awt.Color(0, 0, 0));
        jcGenerosMusicalesActualizarGetCodigoGenero.setForeground(new java.awt.Color(102, 102, 102));
        jcGenerosMusicalesActualizarGetCodigoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Codigo de Genero" }));
        jcGenerosMusicalesActualizarGetCodigoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcGenerosMusicalesActualizarGetCodigoGeneroActionPerformed(evt);
            }
        });
        jpGenerosMusicalesActualizar2.add(jcGenerosMusicalesActualizarGetCodigoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 320, 30));

        jlGeneroRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jpGenerosMusicalesActualizar2.add(jlGeneroRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jtGenerosMusicalesActualizarGetDescGenero.setEditable(false);
        jtGenerosMusicalesActualizarGetDescGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtGenerosMusicalesActualizarGetDescGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtGenerosMusicalesActualizarGetDescGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtGenerosMusicalesActualizarGetDescGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpGenerosMusicalesActualizar2.add(jtGenerosMusicalesActualizarGetDescGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpGenerosMusicalesActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jpGenerosMusicalesActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpGenerosMusicalesActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpGenerosMusicalesActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    public void cargarComboBox() {

        generosMusicalesVarios gmv = new generosMusicalesVarios();

        ArrayList<generosMusicales> generosMusicales;

        generosMusicales = gmv.actualizarGeneroToCombo();

        if (generosMusicales != null) {

            jcGenerosMusicalesActualizarGetCodigoGenero.removeAllItems();

            jcGenerosMusicalesActualizarGetCodigoGenero.addItem("Seleccione un Codigo de Genero");

            for (int i = 0; i < generosMusicales.size(); i++) {

                jcGenerosMusicalesActualizarGetCodigoGenero.addItem(generosMusicales.get(i).getCodigoGenero());

            }

        }

    }

    public void llenadoCampoTexto() {
        String descGenero = "";
        generosMusicalesVarios gmv = new generosMusicalesVarios();

        ArrayList<generosMusicales> generosMusicales;

        generosMusicales = gmv.actualizarGeneroToCombo();

        if (jcGenerosMusicalesActualizarGetCodigoGenero.getSelectedIndex() == 0) {
            jtGenerosMusicalesActualizarGetDescGenero.setText("");
        }

        for (int i = 0; i < generosMusicales.size(); i++) {
            if (generosMusicales.get(i).getCodigoGenero().equals(jcGenerosMusicalesActualizarGetCodigoGenero.getSelectedItem())) {
                descGenero = generosMusicales.get(i).getDescripcionGenero();
                jtGenerosMusicalesActualizarGetDescGenero.setText(descGenero);
            }
        }

    }
    private void jlGenerosMusicalesActualizarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlGenerosMusicalesActualizarExitMouseClicked

    private void jlGenerosMusicalesActualizarExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarExitMouseMoved
        jlGenerosMusicalesActualizarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarExitMouseMoved

    private void jlGenerosMusicalesActualizarExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarExitMouseExited
        jlGenerosMusicalesActualizarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarExitMouseExited

    private void jlGenerosMusicalesActualizarLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarLogoutMouseMoved
        jlGenerosMusicalesActualizarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarLogoutMouseMoved

    private void jlGenerosMusicalesActualizarLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarLogoutMouseExited
        jlGenerosMusicalesActualizarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarLogoutMouseExited

    private void jlGenerosMusicalesActualizarMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarMenuMouseMoved
        jlGenerosMusicalesActualizarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarMenuMouseMoved

    private void jlGenerosMusicalesActualizarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarMenuMouseExited
        jlGenerosMusicalesActualizarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarMenuMouseExited

    private void jlGenerosMusicalesActualizarBotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarBotonActualizarMouseMoved
        jlGenerosMusicalesActualizarBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarBotonActualizarMouseMoved

    private void jlGenerosMusicalesActualizarBotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarBotonActualizarMouseExited
        jlGenerosMusicalesActualizarBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesActualizarBotonActualizarMouseExited


    private void jlGenerosMusicalesActualizarBotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarBotonActualizarMouseClicked
        if (jcGenerosMusicalesActualizarGetCodigoGenero.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Seleccione un Genero", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
        } else {
            if (jtGenerosMusicalesActualizarSetDescGenero.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Por Favor Ingrese la Descripcion del Genero", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
            } else {
                generosMusicales gm = new generosMusicales();
                generosMusicalesVarios gmv = new generosMusicalesVarios();

                ArrayList<generosMusicales> generosMusicales;

                generosMusicales = gmv.actualizarGeneroToCombo();

                boolean generoRepetido = false;

                if (generosMusicales != null) {

                    for (int i = 0; i < generosMusicales.size(); i++) {

                        if (jtGenerosMusicalesActualizarSetDescGenero.getText().toLowerCase().equals(generosMusicales.get(i).getDescripcionGenero())) {
                            generoRepetido = true;
                            break;
                        }
                    }
                    
                    if (generoRepetido == true) {
                        JOptionPane.showMessageDialog(null, "genero ya existe", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                    } else {
                        gm.setCodigoGenero(jcGenerosMusicalesActualizarGetCodigoGenero.getSelectedItem().toString());
                        gm.setDescripcionGenero(jtGenerosMusicalesActualizarSetDescGenero.getText());
                        JOptionPane.showMessageDialog(null, "Genero actualizado correctamente", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                    }
                }

                if (gmv.actualizarGeneroMusical(gm) == true) {
                    jtGenerosMusicalesActualizarSetDescGenero.setText("");
                    jtGenerosMusicalesActualizarGetDescGenero.setText("");
                    jcGenerosMusicalesActualizarGetCodigoGenero.setSelectedItem("Seleccione un Codigo de Genero");
                } else {
                    JOptionPane.showMessageDialog(null, "Falló la actualizacion de genero", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                }
            }
        }
    }//GEN-LAST:event_jlGenerosMusicalesActualizarBotonActualizarMouseClicked

    private void jlGenerosMusicalesActualizarLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarLogoutMouseClicked
        Login l6 = new Login();
        l6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesActualizarLogoutMouseClicked

    private void jlGenerosMusicalesActualizarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesActualizarMenuMouseClicked
        generosMusicalesMenu gmm5 = new generosMusicalesMenu();
        gmm5.setVisible(true);
        gmm5.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesActualizarMenuMouseClicked

    private void jcGenerosMusicalesActualizarGetCodigoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcGenerosMusicalesActualizarGetCodigoGeneroActionPerformed
        llenadoCampoTexto();
    }//GEN-LAST:event_jcGenerosMusicalesActualizarGetCodigoGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generosMusicalesActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcGenerosMusicalesActualizarGetCodigoGenero;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario12;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario5;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario7;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGeneroRegistro;
    private javax.swing.JLabel jlGeneroRegistro1;
    private javax.swing.JLabel jlGenerosMusicalesActualizarBotonActualizar;
    private javax.swing.JLabel jlGenerosMusicalesActualizarExit;
    private javax.swing.JLabel jlGenerosMusicalesActualizarLogout;
    private javax.swing.JLabel jlGenerosMusicalesActualizarMenu;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNextRegistro2;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlNombreRegistro;
    private javax.swing.JPanel jpGenerosMusicalesActualizar1;
    private javax.swing.JPanel jpGenerosMusicalesActualizar2;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin5;
    private javax.swing.JTextField jtGenerosMusicalesActualizarGetDescGenero;
    private javax.swing.JTextField jtGenerosMusicalesActualizarSetDescGenero;
    // End of variables declaration//GEN-END:variables
}
