/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author obarboza
 */
public class generosMusicalesMenu extends javax.swing.JFrame {

    /**
     * Creates new form generosMusicalesMenu
     */
    public generosMusicalesMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jseparadorLogin = new javax.swing.JSeparator();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlGenerosMusicalesMenuExit = new javax.swing.JLabel();
        jlGenerosMusicalesMenuBotonAgregar = new javax.swing.JLabel();
        jlCrearUsuario1 = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlGenerosMusicalesMenuLogout = new javax.swing.JLabel();
        jlCrearUsuario2 = new javax.swing.JLabel();
        jlGenerosMusicalesMenuBotonActualizar = new javax.swing.JLabel();
        jlGenerosMusicalesMenuBotonMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlGenerosMusicalesMenuBotonConsultar = new javax.swing.JLabel();
        jlCrearUsuario4 = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jseparadorLogin.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGenerosMusicalesMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlGenerosMusicalesMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuExitMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlGenerosMusicalesMenuBotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-90.png"))); // NOI18N
        jlGenerosMusicalesMenuBotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuBotonAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonAgregarMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuBotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonAgregarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuBotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, 80));

        jlCrearUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario1.setText("Actualizar Genero");
        jp2MenuRegistro.add(jlCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 10, 80));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlGenerosMusicalesMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlGenerosMusicalesMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuLogoutMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario2.setText("Agregar Genero");
        jp2MenuRegistro.add(jlCrearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jlGenerosMusicalesMenuBotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-update-left-rotation-90.png"))); // NOI18N
        jlGenerosMusicalesMenuBotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuBotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonActualizarMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuBotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonActualizarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuBotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 100, 90));

        jlGenerosMusicalesMenuBotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlGenerosMusicalesMenuBotonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuBotonMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonMenuMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuBotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuBotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlGenerosMusicalesMenuBotonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-consultation-90.png"))); // NOI18N
        jlGenerosMusicalesMenuBotonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesMenuBotonConsultar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonConsultarMouseMoved(evt);
            }
        });
        jlGenerosMusicalesMenuBotonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonConsultarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesMenuBotonConsultarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesMenuBotonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 90));

        jlCrearUsuario4.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario4.setText("Consultar Genero");
        jp2MenuRegistro.add(jlCrearUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-90.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 100, 90));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Generos Musicales");
        jp1MenuRegistro.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    private void jlGenerosMusicalesMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlGenerosMusicalesMenuExitMouseClicked

    private void jlGenerosMusicalesMenuExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuExitMouseMoved
        jlGenerosMusicalesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuExitMouseMoved

    private void jlGenerosMusicalesMenuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuExitMouseExited
        jlGenerosMusicalesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuExitMouseExited

    private void jlGenerosMusicalesMenuLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuLogoutMouseMoved
        jlGenerosMusicalesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuLogoutMouseMoved

    private void jlGenerosMusicalesMenuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuLogoutMouseExited
        jlGenerosMusicalesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuLogoutMouseExited

    private void jlGenerosMusicalesMenuBotonMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonMenuMouseMoved
        jlGenerosMusicalesMenuBotonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonMenuMouseMoved

    private void jlGenerosMusicalesMenuBotonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonMenuMouseExited
        jlGenerosMusicalesMenuBotonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonMenuMouseExited

    private void jlGenerosMusicalesMenuBotonAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonAgregarMouseMoved
        jlGenerosMusicalesMenuBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonAgregarMouseMoved

    private void jlGenerosMusicalesMenuBotonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonAgregarMouseExited
        jlGenerosMusicalesMenuBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonAgregarMouseExited

    private void jlGenerosMusicalesMenuBotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonActualizarMouseMoved
        jlGenerosMusicalesMenuBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonActualizarMouseMoved

    private void jlGenerosMusicalesMenuBotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonActualizarMouseExited
        jlGenerosMusicalesMenuBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonActualizarMouseExited

    private void jlGenerosMusicalesMenuBotonConsultarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonConsultarMouseMoved
        jlGenerosMusicalesMenuBotonConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonConsultarMouseMoved

    private void jlGenerosMusicalesMenuBotonConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonConsultarMouseExited
        jlGenerosMusicalesMenuBotonConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonConsultarMouseExited

    private void jlGenerosMusicalesMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuLogoutMouseClicked
        Login l3 = new Login();
        l3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesMenuLogoutMouseClicked

    private void jlGenerosMusicalesMenuBotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonMenuMouseClicked
        menuOpcionesAdmin o1 = new menuOpcionesAdmin();
        o1.setVisible(true);
        o1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonMenuMouseClicked

    private void jlGenerosMusicalesMenuBotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonAgregarMouseClicked
        generosMusicalesAgregar gma = new generosMusicalesAgregar();
        gma.setVisible(true);
        gma.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonAgregarMouseClicked

    private void jlGenerosMusicalesMenuBotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonActualizarMouseClicked
        generosMusicalesActualizar gmac = new generosMusicalesActualizar();
        gmac.setVisible(true);
        gmac.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonActualizarMouseClicked

    private void jlGenerosMusicalesMenuBotonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesMenuBotonConsultarMouseClicked
        generosMusicalesConsultas gmc = new generosMusicalesConsultas();
        gmc.setVisible(true);
        gmc.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesMenuBotonConsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generosMusicalesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlCrearUsuario1;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario2;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario4;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGenerosMusicalesMenuBotonActualizar;
    private javax.swing.JLabel jlGenerosMusicalesMenuBotonAgregar;
    private javax.swing.JLabel jlGenerosMusicalesMenuBotonConsultar;
    private javax.swing.JLabel jlGenerosMusicalesMenuBotonMenu;
    private javax.swing.JLabel jlGenerosMusicalesMenuExit;
    private javax.swing.JLabel jlGenerosMusicalesMenuLogout;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    // End of variables declaration//GEN-END:variables
}
