/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.generosMusicales;
import entidades.usuario;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logicaNegocio.TextPrompt;
import logicaNegocio.generosMusicalesVarios;

/**
 *
 * @author obarboza
 */
public class generosMusicalesAgregar extends javax.swing.JFrame {

    /**
     * Creates new form generosMusicalesAgregar
     */
    public generosMusicalesAgregar() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt jtCodigoGenero = new TextPrompt("Ingrese Codigo de Genero", jtGenerosMusicalesAgregarSetCodigoGenero);
        TextPrompt jtDescripcionGenero = new TextPrompt("Ingrese Descripcion de Genero", jtGenerosMusicalesAgregarSetDescripcionGenero);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jseparadorLogin5 = new javax.swing.JSeparator();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlNextRegistro2 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlGenerosMusicalesAgregarExit = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlGenerosMusicalesAgregarLogout = new javax.swing.JLabel();
        jlGenerosMusicalesAgregarMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlNombreRegistro = new javax.swing.JLabel();
        jtGenerosMusicalesAgregarSetCodigoGenero = new javax.swing.JTextField();
        jlGeneroRegistro = new javax.swing.JLabel();
        jtGenerosMusicalesAgregarSetDescripcionGenero = new javax.swing.JTextField();
        jlGenerosMusicalesAgregarBotonAgregar = new javax.swing.JLabel();
        jlCrearUsuario4 = new javax.swing.JLabel();
        jlCrearUsuario12 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-60.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 60));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Agregar");
        jp1MenuRegistro.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jseparadorLogin5.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin5.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp1MenuRegistro.add(jseparadorLogin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 10, 50));

        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Generos");
        jp1MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jlNextRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-60.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 60));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGenerosMusicalesAgregarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlGenerosMusicalesAgregarExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesAgregarExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarExitMouseMoved(evt);
            }
        });
        jlGenerosMusicalesAgregarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesAgregarExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlGenerosMusicalesAgregarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlGenerosMusicalesAgregarLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesAgregarLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarLogoutMouseMoved(evt);
            }
        });
        jlGenerosMusicalesAgregarLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesAgregarLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlGenerosMusicalesAgregarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlGenerosMusicalesAgregarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesAgregarMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarMenuMouseMoved(evt);
            }
        });
        jlGenerosMusicalesAgregarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesAgregarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlNombreRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-qr-code-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jtGenerosMusicalesAgregarSetCodigoGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtGenerosMusicalesAgregarSetCodigoGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtGenerosMusicalesAgregarSetCodigoGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtGenerosMusicalesAgregarSetCodigoGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtGenerosMusicalesAgregarSetCodigoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 320, 30));

        jlGeneroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-text-box-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jtGenerosMusicalesAgregarSetDescripcionGenero.setBackground(new java.awt.Color(0, 0, 0));
        jtGenerosMusicalesAgregarSetDescripcionGenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtGenerosMusicalesAgregarSetDescripcionGenero.setForeground(new java.awt.Color(102, 102, 102));
        jtGenerosMusicalesAgregarSetDescripcionGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtGenerosMusicalesAgregarSetDescripcionGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 320, 30));

        jlGenerosMusicalesAgregarBotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-add-database-90.png"))); // NOI18N
        jlGenerosMusicalesAgregarBotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGenerosMusicalesAgregarBotonAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarBotonAgregarMouseMoved(evt);
            }
        });
        jlGenerosMusicalesAgregarBotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarBotonAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlGenerosMusicalesAgregarBotonAgregarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlGenerosMusicalesAgregarBotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jlCrearUsuario4.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario4.setText("Agregar Genero");
        jp2MenuRegistro.add(jlCrearUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jlCrearUsuario12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario12.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario12.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));
    private void jlGenerosMusicalesAgregarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlGenerosMusicalesAgregarExitMouseClicked

    private void jlGenerosMusicalesAgregarExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarExitMouseMoved
        jlGenerosMusicalesAgregarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarExitMouseMoved

    private void jlGenerosMusicalesAgregarExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarExitMouseExited
        jlGenerosMusicalesAgregarExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarExitMouseExited

    private void jlGenerosMusicalesAgregarLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarLogoutMouseMoved
        jlGenerosMusicalesAgregarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarLogoutMouseMoved

    private void jlGenerosMusicalesAgregarLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarLogoutMouseExited
        jlGenerosMusicalesAgregarLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarLogoutMouseExited

    private void jlGenerosMusicalesAgregarMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarMenuMouseMoved
        jlGenerosMusicalesAgregarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarMenuMouseMoved

    private void jlGenerosMusicalesAgregarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarMenuMouseExited
        jlGenerosMusicalesAgregarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarMenuMouseExited

    private void jlGenerosMusicalesAgregarBotonAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarBotonAgregarMouseMoved
        jlGenerosMusicalesAgregarBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarBotonAgregarMouseMoved

    private void jlGenerosMusicalesAgregarBotonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarBotonAgregarMouseExited
        jlGenerosMusicalesAgregarBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlGenerosMusicalesAgregarBotonAgregarMouseExited

    private void jlGenerosMusicalesAgregarBotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarBotonAgregarMouseClicked
        if (jtGenerosMusicalesAgregarSetCodigoGenero.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Codigo del Genero","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
        } else {
            if (jtGenerosMusicalesAgregarSetDescripcionGenero.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Por Favor Ingrese la Descripcion del Genero","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
            } else {
                generosMusicales gen = new generosMusicales();
                generosMusicalesVarios l1 = new generosMusicalesVarios();

                ArrayList<generosMusicales> generosMusicales;

                generosMusicales = l1.actualizarGeneroToCombo();

                boolean generoRepetido = false;

                if (generosMusicales != null) {

                    for (int i = 0; i < generosMusicales.size(); i++) {

                        if (jtGenerosMusicalesAgregarSetCodigoGenero.getText().toLowerCase().equals(generosMusicales.get(i).getCodigoGenero())) {
                            generoRepetido = true;
                        } else {
                            if (jtGenerosMusicalesAgregarSetDescripcionGenero.getText().toLowerCase().equals(generosMusicales.get(i).getDescripcionGenero())) {
                                generoRepetido = true;
                                break;
                            }
                        }
                    }

                    if (generoRepetido == true) {
                        JOptionPane.showMessageDialog(null, "Descripcion o codigo de genero repetidos","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                    } else {
                        gen.setCodigoGenero(jtGenerosMusicalesAgregarSetCodigoGenero.getText());
                        gen.setDescripcionGenero(jtGenerosMusicalesAgregarSetDescripcionGenero.getText());
                    }
                }

                if (l1.ingresarGeneroMusical(gen) == true) {
                    JOptionPane.showMessageDialog(null, "Genero musical agregado correctamente","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                    jtGenerosMusicalesAgregarSetDescripcionGenero.setText("");
                    jtGenerosMusicalesAgregarSetCodigoGenero.setText("");

                } else {
                    JOptionPane.showMessageDialog(null, "Falló al agregar el genero musical","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                    jtGenerosMusicalesAgregarSetDescripcionGenero.setText("");
                    jtGenerosMusicalesAgregarSetCodigoGenero.setText("");
                }
            }
        }
    }//GEN-LAST:event_jlGenerosMusicalesAgregarBotonAgregarMouseClicked

    private void jlGenerosMusicalesAgregarLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarLogoutMouseClicked
        Login l5 = new Login();
        l5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesAgregarLogoutMouseClicked

    private void jlGenerosMusicalesAgregarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGenerosMusicalesAgregarMenuMouseClicked
        generosMusicalesMenu gmm2 = new generosMusicalesMenu();
        gmm2.setVisible(true);
        gmm2.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlGenerosMusicalesAgregarMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generosMusicalesAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generosMusicalesAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario12;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario4;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGeneroRegistro;
    private javax.swing.JLabel jlGenerosMusicalesAgregarBotonAgregar;
    private javax.swing.JLabel jlGenerosMusicalesAgregarExit;
    private javax.swing.JLabel jlGenerosMusicalesAgregarLogout;
    private javax.swing.JLabel jlGenerosMusicalesAgregarMenu;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNextRegistro2;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlNombreRegistro;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin5;
    private javax.swing.JTextField jtGenerosMusicalesAgregarSetCodigoGenero;
    private javax.swing.JTextField jtGenerosMusicalesAgregarSetDescripcionGenero;
    // End of variables declaration//GEN-END:variables
}
