/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author obarboza
 */
public class MenuRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistroUsuario
     */
    public MenuRegistroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlMenuRegistroExit = new javax.swing.JLabel();
        jlMenuRegistroUsuarioBotonActualizar = new javax.swing.JLabel();
        jlMenuRegistroUsuarioBotonAgregar = new javax.swing.JLabel();
        jlCrearUsuario = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlMenuRegistroLogout = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jlRegistroUsuarioMenu = new javax.swing.JLabel();
        jlCrearUsuario12 = new javax.swing.JLabel();
        jseparadorLogin = new javax.swing.JSeparator();
        jlCrearUsuario2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 240));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jp1MenuRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMenuRegistroExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlMenuRegistroExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuRegistroExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuRegistroExitMouseMoved(evt);
            }
        });
        jlMenuRegistroExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuRegistroExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuRegistroExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuRegistroExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlMenuRegistroUsuarioBotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-registration-90.png"))); // NOI18N
        jlMenuRegistroUsuarioBotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuRegistroUsuarioBotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonActualizarMouseMoved(evt);
            }
        });
        jlMenuRegistroUsuarioBotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonActualizarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuRegistroUsuarioBotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 100, 90));

        jlMenuRegistroUsuarioBotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-90.png"))); // NOI18N
        jlMenuRegistroUsuarioBotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuRegistroUsuarioBotonAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonAgregarMouseMoved(evt);
            }
        });
        jlMenuRegistroUsuarioBotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuRegistroUsuarioBotonAgregarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuRegistroUsuarioBotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, 80));

        jlCrearUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario.setText("Agregar Usuario");
        jp2MenuRegistro.add(jlCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 10, 80));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlMenuRegistroLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlMenuRegistroLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuRegistroLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuRegistroLogoutMouseMoved(evt);
            }
        });
        jlMenuRegistroLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuRegistroLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuRegistroLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuRegistroLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jlRegistroUsuarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlRegistroUsuarioMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRegistroUsuarioMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioMenuMouseMoved(evt);
            }
        });
        jlRegistroUsuarioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlRegistroUsuarioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jlCrearUsuario12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario12.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario12.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jseparadorLogin.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlCrearUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario2.setText("Actualizar Datos");
        jp2MenuRegistro.add(jlCrearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    private void jlMenuRegistroExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlMenuRegistroExitMouseClicked

    private void jlMenuRegistroUsuarioBotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonActualizarMouseMoved
        jlMenuRegistroUsuarioBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonActualizarMouseMoved

    private void jlMenuRegistroUsuarioBotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonActualizarMouseExited
        jlMenuRegistroUsuarioBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonActualizarMouseExited

    private void jlMenuRegistroUsuarioBotonAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonAgregarMouseMoved
        jlMenuRegistroUsuarioBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonAgregarMouseMoved

    private void jlMenuRegistroUsuarioBotonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonAgregarMouseExited
        jlMenuRegistroUsuarioBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonAgregarMouseExited

    private void jlMenuRegistroExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroExitMouseMoved
        jlMenuRegistroExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuRegistroExitMouseMoved

    private void jlMenuRegistroExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroExitMouseExited
        jlMenuRegistroExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuRegistroExitMouseExited

    private void jlMenuRegistroLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroLogoutMouseClicked
        Login l31 = new Login();

        l31.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlMenuRegistroLogoutMouseClicked

    private void jlMenuRegistroUsuarioBotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonAgregarMouseClicked
        RegistroUsuarioAdmin r1 = new RegistroUsuarioAdmin();
        r1.setVisible(true);
        this.setVisible(false);
        r1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonAgregarMouseClicked

    private void jlMenuRegistroUsuarioBotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroUsuarioBotonActualizarMouseClicked
        ActualizarUsuario1Admin a1 = new ActualizarUsuario1Admin();
        a1.setVisible(true);
        a1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlMenuRegistroUsuarioBotonActualizarMouseClicked

    private void jlMenuRegistroLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroLogoutMouseMoved
        jlMenuRegistroLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuRegistroLogoutMouseMoved

    private void jlMenuRegistroLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuRegistroLogoutMouseExited
        jlMenuRegistroLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuRegistroLogoutMouseExited

    private void jlRegistroUsuarioMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioMenuMouseMoved
        jlRegistroUsuarioMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlRegistroUsuarioMenuMouseMoved

    private void jlRegistroUsuarioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioMenuMouseClicked
        menuOpcionesAdmin moa = new menuOpcionesAdmin();
        moa.setVisible(true);
        this.setVisible(false);
        moa.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
    }//GEN-LAST:event_jlRegistroUsuarioMenuMouseClicked

    private void jlRegistroUsuarioMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioMenuMouseExited
        jlRegistroUsuarioMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlRegistroUsuarioMenuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlCrearUsuario;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario12;
    private javax.swing.JLabel jlCrearUsuario2;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlMenuRegistroExit;
    private javax.swing.JLabel jlMenuRegistroLogout;
    private javax.swing.JLabel jlMenuRegistroUsuarioBotonActualizar;
    private javax.swing.JLabel jlMenuRegistroUsuarioBotonAgregar;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlRegistroUsuarioMenu;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    // End of variables declaration//GEN-END:variables
}
