package presentacion;

import entidades.usuario;
import javax.swing.JOptionPane;

public class menuOpcionesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuOpcionesAdmin
     */
    public menuOpcionesAdmin() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlMenuOpcionesAdminExit = new javax.swing.JLabel();
        jlMenuOpcionesAdminLogout = new javax.swing.JLabel();
        jp2MenuRegistro1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlMenuOpcionesAdminBotonCanciones = new javax.swing.JLabel();
        jlMenuOpcionesAdminBotonGenerosMusicales = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jlCrearUsuario4 = new javax.swing.JLabel();
        jlMenuOpcionesAdminBotonVenta = new javax.swing.JLabel();
        jlMenuOpcionesAdminBotonActualizar = new javax.swing.JLabel();
        jlMenuOpcionesAdminBotonReportes = new javax.swing.JLabel();
        jlCrearUsuario7 = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlCrearUsuario1 = new javax.swing.JLabel();
        jlCrearUsuario2 = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jseparadorLogin7 = new javax.swing.JSeparator();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("Admin");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMenuOpcionesAdminExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlMenuOpcionesAdminExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminExitMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuOpcionesAdminExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlMenuOpcionesAdminLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlMenuOpcionesAdminLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminLogoutMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlMenuOpcionesAdminLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jp2MenuRegistro1.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jp2MenuRegistro1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlMenuOpcionesAdminBotonCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-library-90.png"))); // NOI18N
        jlMenuOpcionesAdminBotonCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminBotonCanciones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonCancionesMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminBotonCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonCancionesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonCancionesMouseExited(evt);
            }
        });
        jp2MenuRegistro1.add(jlMenuOpcionesAdminBotonCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 90, 90));

        jlMenuOpcionesAdminBotonGenerosMusicales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-90.png"))); // NOI18N
        jlMenuOpcionesAdminBotonGenerosMusicales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminBotonGenerosMusicales.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonGenerosMusicalesMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminBotonGenerosMusicales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonGenerosMusicalesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonGenerosMusicalesMouseExited(evt);
            }
        });
        jp2MenuRegistro1.add(jlMenuOpcionesAdminBotonGenerosMusicales, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 80, 80));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Canciones");
        jp2MenuRegistro1.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 210, -1, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro1.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        jp2MenuRegistro1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario4.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario4.setText("Generos Musicales");
        jp2MenuRegistro1.add(jlCrearUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jlMenuOpcionesAdminBotonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-shopping-90.png"))); // NOI18N
        jlMenuOpcionesAdminBotonVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminBotonVenta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonVentaMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminBotonVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonVentaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonVentaMouseExited(evt);
            }
        });
        jp2MenuRegistro1.add(jlMenuOpcionesAdminBotonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 80));

        jlMenuOpcionesAdminBotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-registration-90.png"))); // NOI18N
        jlMenuOpcionesAdminBotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminBotonActualizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonActualizarMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminBotonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonActualizarMouseExited(evt);
            }
        });
        jp2MenuRegistro1.add(jlMenuOpcionesAdminBotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 100, 90));

        jlMenuOpcionesAdminBotonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-graph-report-90.png"))); // NOI18N
        jlMenuOpcionesAdminBotonReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenuOpcionesAdminBotonReportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonReportesMouseMoved(evt);
            }
        });
        jlMenuOpcionesAdminBotonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonReportesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMenuOpcionesAdminBotonReportesMouseExited(evt);
            }
        });
        jp2MenuRegistro1.add(jlMenuOpcionesAdminBotonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 90, 80));

        jlCrearUsuario7.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario7.setText("Reportes");
        jp2MenuRegistro1.add(jlCrearUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 503, -1, -1));

        jlLogin.setBackground(new java.awt.Color(51, 51, 51));
        jlLogin.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(135, 211, 124));
        jlLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogin.setText("Menu ");
        jp2MenuRegistro1.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jlCrearUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario1.setText("Menu Registro Usuario");
        jp2MenuRegistro1.add(jlCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jlCrearUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario2.setText("Venta de Canciones");
        jp2MenuRegistro1.add(jlCrearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro1.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 230, 10, 60));

        jseparadorLogin7.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin7.setForeground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro1.add(jseparadorLogin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 60, 10));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro1.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro1.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro1.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 10, 20));

        jp2MenuRegistro.add(jp2MenuRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }


    private void jlMenuOpcionesAdminExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlMenuOpcionesAdminExitMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jlMenuOpcionesAdminExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminExitMouseMoved
        jlMenuOpcionesAdminExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminExitMouseMoved

    private void jlMenuOpcionesAdminExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminExitMouseExited
        jlMenuOpcionesAdminExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminExitMouseExited

    private void jlMenuOpcionesAdminLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminLogoutMouseMoved
        jlMenuOpcionesAdminLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminLogoutMouseMoved

    private void jlMenuOpcionesAdminLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminLogoutMouseExited
        jlMenuOpcionesAdminLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminLogoutMouseExited

    private void jlMenuOpcionesAdminBotonGenerosMusicalesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseMoved
        jlMenuOpcionesAdminBotonGenerosMusicales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseMoved

    private void jlMenuOpcionesAdminBotonGenerosMusicalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseExited
        jlMenuOpcionesAdminBotonGenerosMusicales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseExited

    private void jlMenuOpcionesAdminBotonCancionesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonCancionesMouseMoved
        jlMenuOpcionesAdminBotonCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonCancionesMouseMoved

    private void jlMenuOpcionesAdminBotonCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonCancionesMouseExited
        jlMenuOpcionesAdminBotonCanciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonCancionesMouseExited

    private void jlMenuOpcionesAdminBotonVentaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonVentaMouseMoved
        jlMenuOpcionesAdminBotonVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonVentaMouseMoved

    private void jlMenuOpcionesAdminBotonVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonVentaMouseExited
        jlMenuOpcionesAdminBotonVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonVentaMouseExited

    private void jlMenuOpcionesAdminBotonActualizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonActualizarMouseMoved
        jlMenuOpcionesAdminBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonActualizarMouseMoved

    private void jlMenuOpcionesAdminBotonActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonActualizarMouseExited
        jlMenuOpcionesAdminBotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonActualizarMouseExited

    private void jlMenuOpcionesAdminBotonReportesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonReportesMouseMoved
        jlMenuOpcionesAdminBotonReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonReportesMouseMoved

    private void jlMenuOpcionesAdminBotonReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonReportesMouseExited
        jlMenuOpcionesAdminBotonReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonReportesMouseExited

    private void jlMenuOpcionesAdminLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminLogoutMouseClicked
        Login l1 = new Login();
        l1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlMenuOpcionesAdminLogoutMouseClicked

    private void jlMenuOpcionesAdminBotonGenerosMusicalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseClicked
        generosMusicalesMenu m1 = new generosMusicalesMenu();
        m1.setVisible(true);
        m1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonGenerosMusicalesMouseClicked

    private void jlMenuOpcionesAdminBotonCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonCancionesMouseClicked
        cancionesMenu c1 = new cancionesMenu();
        c1.setVisible(true);
        c1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonCancionesMouseClicked

    private void jlMenuOpcionesAdminBotonVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonVentaMouseClicked
        ventas v1 = new ventas();
        v1.setVisible(true);
        v1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonVentaMouseClicked

    private void jlMenuOpcionesAdminBotonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonActualizarMouseClicked
        MenuRegistroUsuario a1 = new MenuRegistroUsuario();
        a1.setVisible(true);
        a1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonActualizarMouseClicked

    private void jlMenuOpcionesAdminBotonReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuOpcionesAdminBotonReportesMouseClicked
        reportesMenu r1 = new reportesMenu();
        r1.setVisible(true);
        r1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jlMenuOpcionesAdminBotonReportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuOpcionesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlCrearUsuario1;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario2;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario4;
    private javax.swing.JLabel jlCrearUsuario7;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlMenuOpcionesAdminBotonActualizar;
    private javax.swing.JLabel jlMenuOpcionesAdminBotonCanciones;
    private javax.swing.JLabel jlMenuOpcionesAdminBotonGenerosMusicales;
    private javax.swing.JLabel jlMenuOpcionesAdminBotonReportes;
    private javax.swing.JLabel jlMenuOpcionesAdminBotonVenta;
    private javax.swing.JLabel jlMenuOpcionesAdminExit;
    private javax.swing.JLabel jlMenuOpcionesAdminLogout;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro1;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin7;
    // End of variables declaration//GEN-END:variables
}
