package presentacion;

import entidades.*;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logicaNegocio.TextPrompt;
import logicaNegocio.registroUsuario;
import logicaNegocio.reportesVarios;

public class RegistroUsuario extends javax.swing.JFrame {

    public RegistroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt jtUserID = new TextPrompt("Ingrese su numero de identificacion", jtRegistroUsuarioSetID);
        TextPrompt jtNombreUsuario = new TextPrompt("Ingrese su Nombre Completo", jtRegistroUsuarioSetNombre);
        TextPrompt jtCorreo = new TextPrompt("Ingrese su Correo Electronico", jtRegistroUsuarioSetCorreo);
        TextPrompt jtNumeroTarjeta = new TextPrompt("Ingrese su Numero de tarjeta de 16 digitos", jtRegistroUsuarioSetNumeroTarjeta);
        TextPrompt jtpass = new TextPrompt("Ingrese su Contraseña", jtRegistroUsuarioSetPassword);
        llenadoCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1Registro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlRegistroUsuarioBotonAgregar = new javax.swing.JLabel();
        jlCrearUsuario = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jp2Registro = new javax.swing.JPanel();
        jlRegistroUsuarioExit = new javax.swing.JLabel();
        jtRegistroUsuarioSetPassword = new javax.swing.JPasswordField();
        jlIDRegistro = new javax.swing.JLabel();
        jlPassRegistro = new javax.swing.JLabel();
        jtRegistroUsuarioSetID = new javax.swing.JTextField();
        jlNumeroTarjetaRegistro = new javax.swing.JLabel();
        jtRegistroUsuarioSetNombre = new javax.swing.JTextField();
        jlNombreRegistro = new javax.swing.JLabel();
        jlGeneroRegistro = new javax.swing.JLabel();
        jtRegistroUsuarioSetCorreo = new javax.swing.JTextField();
        jlCorreoRegistro = new javax.swing.JLabel();
        jlTipoTarjetaRegistro = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jlRegistroUsuarioLogout = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jcRegistroUsuarioSetGenero = new javax.swing.JComboBox<>();
        jcRegistroUsuarioSetTipoTarjeta1 = new javax.swing.JComboBox<>();
        jlIDRegistro1 = new javax.swing.JLabel();
        jtRegistroUsuarioGetPerfil = new javax.swing.JTextField();
        jtRegistroUsuarioSetNumeroTarjeta = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp1Registro.setBackground(new java.awt.Color(0, 0, 0));
        jp1Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1Registro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jlRegistroUsuarioBotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-90.png"))); // NOI18N
        jlRegistroUsuarioBotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRegistroUsuarioBotonAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioBotonAgregarMouseMoved(evt);
            }
        });
        jlRegistroUsuarioBotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioBotonAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioBotonAgregarMouseExited(evt);
            }
        });
        jp1Registro.add(jlRegistroUsuarioBotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 80));

        jlCrearUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario.setText("Agregar Usuario");
        jp1Registro.add(jlCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jp1Registro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1Registro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jp1Registro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jp1Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        jp2Registro.setBackground(new java.awt.Color(51, 51, 51));
        jp2Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlRegistroUsuarioExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlRegistroUsuarioExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRegistroUsuarioExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioExitMouseMoved(evt);
            }
        });
        jlRegistroUsuarioExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioExitMouseExited(evt);
            }
        });
        jp2Registro.add(jlRegistroUsuarioExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jtRegistroUsuarioSetPassword.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioSetPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtRegistroUsuarioSetPassword.setForeground(new java.awt.Color(102, 102, 102));
        jtRegistroUsuarioSetPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2Registro.add(jtRegistroUsuarioSetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 320, 30));

        jlIDRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_ID.png"))); // NOI18N
        jp2Registro.add(jlIDRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlPassRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_lock.png"))); // NOI18N
        jp2Registro.add(jlPassRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jtRegistroUsuarioSetID.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioSetID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtRegistroUsuarioSetID.setForeground(new java.awt.Color(102, 102, 102));
        jtRegistroUsuarioSetID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2Registro.add(jtRegistroUsuarioSetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 320, 30));

        jlNumeroTarjetaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_cardPayment.png"))); // NOI18N
        jp2Registro.add(jlNumeroTarjetaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jtRegistroUsuarioSetNombre.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioSetNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtRegistroUsuarioSetNombre.setForeground(new java.awt.Color(102, 102, 102));
        jtRegistroUsuarioSetNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2Registro.add(jtRegistroUsuarioSetNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 30));

        jlNombreRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jp2Registro.add(jlNombreRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jlGeneroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_male_female.png"))); // NOI18N
        jp2Registro.add(jlGeneroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jtRegistroUsuarioSetCorreo.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioSetCorreo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtRegistroUsuarioSetCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jtRegistroUsuarioSetCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2Registro.add(jtRegistroUsuarioSetCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 320, 30));

        jlCorreoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_email.png"))); // NOI18N
        jp2Registro.add(jlCorreoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jlTipoTarjetaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_visa.png"))); // NOI18N
        jp2Registro.add(jlTipoTarjetaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2Registro.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlRegistroUsuarioLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlRegistroUsuarioLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRegistroUsuarioLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioLogoutMouseMoved(evt);
            }
        });
        jlRegistroUsuarioLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRegistroUsuarioLogoutMouseExited(evt);
            }
        });
        jp2Registro.add(jlRegistroUsuarioLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Login");
        jp2Registro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2Registro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        jcRegistroUsuarioSetGenero.setBackground(new java.awt.Color(0, 0, 0));
        jcRegistroUsuarioSetGenero.setForeground(new java.awt.Color(102, 102, 102));
        jcRegistroUsuarioSetGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp2Registro.add(jcRegistroUsuarioSetGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 320, 30));

        jcRegistroUsuarioSetTipoTarjeta1.setBackground(new java.awt.Color(0, 0, 0));
        jcRegistroUsuarioSetTipoTarjeta1.setForeground(new java.awt.Color(102, 102, 102));
        jcRegistroUsuarioSetTipoTarjeta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp2Registro.add(jcRegistroUsuarioSetTipoTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 320, 30));

        jlIDRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_checkUser.png"))); // NOI18N
        jp2Registro.add(jlIDRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jtRegistroUsuarioGetPerfil.setEditable(false);
        jtRegistroUsuarioGetPerfil.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioGetPerfil.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtRegistroUsuarioGetPerfil.setForeground(new java.awt.Color(102, 102, 102));
        jtRegistroUsuarioGetPerfil.setText("Usuario");
        jtRegistroUsuarioGetPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2Registro.add(jtRegistroUsuarioGetPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 320, 30));

        jtRegistroUsuarioSetNumeroTarjeta.setBackground(new java.awt.Color(0, 0, 0));
        jtRegistroUsuarioSetNumeroTarjeta.setBorder(null);
        jtRegistroUsuarioSetNumeroTarjeta.setForeground(new java.awt.Color(102, 102, 102));
        try {
            jtRegistroUsuarioSetNumeroTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtRegistroUsuarioSetNumeroTarjeta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jp2Registro.add(jtRegistroUsuarioSetNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 320, 30));

        getContentPane().add(jp2Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 470, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));
    private void jlRegistroUsuarioExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlRegistroUsuarioExitMouseClicked

    private void jlRegistroUsuarioLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioLogoutMouseClicked
        Login l1 = new Login();

        l1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlRegistroUsuarioLogoutMouseClicked

    private void jlRegistroUsuarioBotonAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioBotonAgregarMouseMoved
        jlRegistroUsuarioBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlRegistroUsuarioBotonAgregarMouseMoved

    private void jlRegistroUsuarioExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioExitMouseMoved
        jlRegistroUsuarioExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlRegistroUsuarioExitMouseMoved

    private void jlRegistroUsuarioExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioExitMouseExited
        jlRegistroUsuarioExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlRegistroUsuarioExitMouseExited

    private void jlRegistroUsuarioLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioLogoutMouseMoved
        jlRegistroUsuarioLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlRegistroUsuarioLogoutMouseMoved

    private void jlRegistroUsuarioLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioLogoutMouseExited
        jlRegistroUsuarioLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlRegistroUsuarioLogoutMouseExited

    private void jlRegistroUsuarioBotonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioBotonAgregarMouseExited
        jlRegistroUsuarioBotonAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jlRegistroUsuarioBotonAgregarMouseExited

    public void llenadoCombo() {
        jcRegistroUsuarioSetGenero.addItem("Seleccione Genero");
        jcRegistroUsuarioSetGenero.addItem("Masculino");
        jcRegistroUsuarioSetGenero.addItem("Femenino");

        jcRegistroUsuarioSetTipoTarjeta1.addItem("Seleccione Tipo de Tarjeta");
        jcRegistroUsuarioSetTipoTarjeta1.addItem("VISA");
        jcRegistroUsuarioSetTipoTarjeta1.addItem("MASTERCARD");
        jcRegistroUsuarioSetTipoTarjeta1.addItem("AMERICAN EXPRESS");
    }
    private void jlRegistroUsuarioBotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroUsuarioBotonAgregarMouseClicked
        Pattern patron = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        if (jtRegistroUsuarioSetID.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese el ID","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
        } else {
            if (jtRegistroUsuarioSetNombre.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Nombre Completo","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
            } else {
                if (jcRegistroUsuarioSetGenero.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Por Favor Seleccionar Genero","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                } else {
                    if (jtRegistroUsuarioSetCorreo.getText().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Correo Electronico","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                    } else {
                        Matcher correo = patron.matcher(jtRegistroUsuarioSetCorreo.getText());
                        if (correo.find() != true) {
                            JOptionPane.showMessageDialog(null, "Por Favor Digite un correo valido","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                        } else {
                            if (jcRegistroUsuarioSetTipoTarjeta1.getSelectedIndex() == 0) {
                                JOptionPane.showMessageDialog(null, "Por Favor Seleccione un Tipo de Tarjeta","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                            } else {
                                if (jtRegistroUsuarioSetNumeroTarjeta.getText().length() == 0) {
                                    JOptionPane.showMessageDialog(null, "Por Favor Ingrese el Numero de Tarjeta","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                                } else {
                                    if (jtRegistroUsuarioSetPassword.getText().length() == 0) {
                                        JOptionPane.showMessageDialog(null, "Por Favor Ingrese la Contraseña","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                                    } else {

                                        usuario usr = new usuario();
                                        registroUsuario l1 = new registroUsuario();
                                        reportesVarios rv = new reportesVarios();

                                        ArrayList<usuario> usuarios;

                                        usuarios = rv.reporteUsuario();

                                        boolean generoRepetido = false;

                                        if (usuarios != null) {

                                            for (int i = 0; i < usuarios.size(); i++) {

                                                if (jtRegistroUsuarioSetID.getText().toLowerCase().equals(usuarios.get(i).getIdentificacionUsuario())) {
                                                    generoRepetido = true;
                                                }
                                            }

                                            if (generoRepetido == true) {
                                                JOptionPane.showMessageDialog(null, "Usuario ya existe en el sistema","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                                            } else {
                                                usr.setIdentificacionUsuario(jtRegistroUsuarioSetID.getText());
                                                usr.setNombreCompletoUsuario(jtRegistroUsuarioSetNombre.getText());
                                                usr.setGeneroUsuario(jcRegistroUsuarioSetGenero.getSelectedItem().toString());
                                                usr.setCorreoElectronicoUsuario(jtRegistroUsuarioSetCorreo.getText());
                                                usr.setTipoTarjetaUsuario(jcRegistroUsuarioSetTipoTarjeta1.getSelectedItem().toString());
                                                usr.setNumeroTarjetaUsuario(jtRegistroUsuarioSetNumeroTarjeta.getText());
                                                usr.setContrasenaUsuario(jtRegistroUsuarioSetPassword.getText());
                                                usr.setPerfilUsuario(jtRegistroUsuarioGetPerfil.getText());

                                            }
                                        }

                                        if (l1.ingresarUsuarioSistema(usr) == true) {
                                            JOptionPane.showMessageDialog(null, "Usuario agregado correctamente","La Venta Musical",JOptionPane.INFORMATION_MESSAGE,m);
                                            jtRegistroUsuarioSetID.setText("");
                                            jtRegistroUsuarioSetID.setEnabled(false);
                                            jtRegistroUsuarioSetNombre.setText("");
                                            jtRegistroUsuarioSetNombre.setEnabled(false);
                                            jcRegistroUsuarioSetGenero.setSelectedItem("Seleccione Genero");
                                            jtRegistroUsuarioSetCorreo.setText("");
                                            jtRegistroUsuarioSetCorreo.setEnabled(false);
                                            jcRegistroUsuarioSetTipoTarjeta1.setSelectedItem("Seleccione Tipo de Tarjeta");
                                            jtRegistroUsuarioSetNumeroTarjeta.setText("");
                                            jtRegistroUsuarioSetNumeroTarjeta.setEnabled(false);
                                            jtRegistroUsuarioSetPassword.setText("");
                                            jtRegistroUsuarioSetPassword.setEnabled(false);
                                        } else {
                                            //JOptionPane.showMessageDialog(null, "Falló al agregar el usuario");
                                            jtRegistroUsuarioSetID.setText("");
                                            jtRegistroUsuarioSetNombre.setText("");
                                            jcRegistroUsuarioSetGenero.setSelectedItem("Seleccione Genero");
                                            jtRegistroUsuarioSetCorreo.setText("");
                                            jcRegistroUsuarioSetTipoTarjeta1.setSelectedItem("Seleccione Tipo de Tarjeta");
                                            jtRegistroUsuarioSetNumeroTarjeta.setText("");
                                            jtRegistroUsuarioSetPassword.setText("");

                                        }
                                    }
                                }

                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jlRegistroUsuarioBotonAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcRegistroUsuarioSetGenero;
    private javax.swing.JComboBox<String> jcRegistroUsuarioSetTipoTarjeta1;
    private javax.swing.JLabel jlCorreoRegistro;
    private javax.swing.JLabel jlCrearUsuario;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGeneroRegistro;
    private javax.swing.JLabel jlIDRegistro;
    private javax.swing.JLabel jlIDRegistro1;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlNombreRegistro;
    private javax.swing.JLabel jlNumeroTarjetaRegistro;
    private javax.swing.JLabel jlPassRegistro;
    private javax.swing.JLabel jlRegistroUsuarioBotonAgregar;
    private javax.swing.JLabel jlRegistroUsuarioExit;
    private javax.swing.JLabel jlRegistroUsuarioLogout;
    private javax.swing.JLabel jlTipoTarjetaRegistro;
    private javax.swing.JPanel jp1Registro;
    private javax.swing.JPanel jp2Registro;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JTextField jtRegistroUsuarioGetPerfil;
    private javax.swing.JTextField jtRegistroUsuarioSetCorreo;
    private javax.swing.JTextField jtRegistroUsuarioSetID;
    private javax.swing.JTextField jtRegistroUsuarioSetNombre;
    private javax.swing.JFormattedTextField jtRegistroUsuarioSetNumeroTarjeta;
    private javax.swing.JPasswordField jtRegistroUsuarioSetPassword;
    // End of variables declaration//GEN-END:variables
}
