/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;
import logicaNegocio.reportesVarios;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author obarboza
 */
public class reportesMenu extends javax.swing.JFrame {

    /**
     * Creates new form reportesMenu
     */
    public reportesMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlNextRegistro = new javax.swing.JLabel();
        jlCrearUsuario3 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlReportesMenuExit = new javax.swing.JLabel();
        jlReportesMenuBotonUsuariosRegistrados = new javax.swing.JLabel();
        jlCrearUsuario1 = new javax.swing.JLabel();
        jseparadorLogin1 = new javax.swing.JSeparator();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlReportesMenuLogout = new javax.swing.JLabel();
        jlCrearUsuario2 = new javax.swing.JLabel();
        jlReportesMenuBotonCancionesVendidas = new javax.swing.JLabel();
        jlReportesMenuBotonMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlReportesMenuBotonFacturasRealizadas = new javax.swing.JLabel();
        jlCrearUsuario4 = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 240));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 10));

        jlNextRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-graph-report-90.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 90));

        jlCrearUsuario3.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario3.setText("Reportes");
        jp1MenuRegistro.add(jlCrearUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlReportesMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlReportesMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuExitMouseMoved(evt);
            }
        });
        jlReportesMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jlReportesMenuBotonUsuariosRegistrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-registration-90.png"))); // NOI18N
        jlReportesMenuBotonUsuariosRegistrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuBotonUsuariosRegistrados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonUsuariosRegistradosMouseMoved(evt);
            }
        });
        jlReportesMenuBotonUsuariosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonUsuariosRegistradosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonUsuariosRegistradosMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuBotonUsuariosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, 80));

        jlCrearUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario1.setText("Canciones Vendidas");
        jp2MenuRegistro.add(jlCrearUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jseparadorLogin1.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin1.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 10, 80));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, 10, 24));

        jlReportesMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlReportesMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuLogoutMouseMoved(evt);
            }
        });
        jlReportesMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, -1));

        jlCrearUsuario2.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario2.setText("Usuarios Registrados");
        jp2MenuRegistro.add(jlCrearUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jlReportesMenuBotonCancionesVendidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-music-90.png"))); // NOI18N
        jlReportesMenuBotonCancionesVendidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuBotonCancionesVendidas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonCancionesVendidasMouseMoved(evt);
            }
        });
        jlReportesMenuBotonCancionesVendidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonCancionesVendidasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonCancionesVendidasMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuBotonCancionesVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 80));

        jlReportesMenuBotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlReportesMenuBotonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuBotonMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonMenuMouseMoved(evt);
            }
        });
        jlReportesMenuBotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuBotonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, 10, 24));

        jlReportesMenuBotonFacturasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-purchase-order-90.png"))); // NOI18N
        jlReportesMenuBotonFacturasRealizadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlReportesMenuBotonFacturasRealizadas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonFacturasRealizadasMouseMoved(evt);
            }
        });
        jlReportesMenuBotonFacturasRealizadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonFacturasRealizadasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlReportesMenuBotonFacturasRealizadasMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlReportesMenuBotonFacturasRealizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, 90));

        jlCrearUsuario4.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario4.setText("Facturas Realizadas");
        jp2MenuRegistro.add(jlCrearUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jp1MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp2MenuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
    }

    private void jlReportesMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlReportesMenuExitMouseClicked

    private void jlReportesMenuExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuExitMouseMoved
        jlReportesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuExitMouseMoved

    private void jlReportesMenuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuExitMouseExited
        jlReportesMenuExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuExitMouseExited

    private void jlReportesMenuLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuLogoutMouseMoved
        jlReportesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuLogoutMouseMoved

    private void jlReportesMenuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuLogoutMouseExited
        jlReportesMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuLogoutMouseExited

    private void jlReportesMenuBotonMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonMenuMouseMoved
        jlReportesMenuBotonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuBotonMenuMouseMoved

    private void jlReportesMenuBotonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonMenuMouseExited
        jlReportesMenuBotonMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuBotonMenuMouseExited

    private void jlReportesMenuBotonUsuariosRegistradosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonUsuariosRegistradosMouseMoved
        jlReportesMenuBotonUsuariosRegistrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuBotonUsuariosRegistradosMouseMoved

    private void jlReportesMenuBotonUsuariosRegistradosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonUsuariosRegistradosMouseExited
        jlReportesMenuBotonUsuariosRegistrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuBotonUsuariosRegistradosMouseExited

    private void jlReportesMenuBotonCancionesVendidasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonCancionesVendidasMouseMoved
        jlReportesMenuBotonCancionesVendidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuBotonCancionesVendidasMouseMoved

    private void jlReportesMenuBotonCancionesVendidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonCancionesVendidasMouseExited
        jlReportesMenuBotonCancionesVendidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuBotonCancionesVendidasMouseExited

    private void jlReportesMenuBotonFacturasRealizadasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonFacturasRealizadasMouseMoved
        jlReportesMenuBotonFacturasRealizadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlReportesMenuBotonFacturasRealizadasMouseMoved

    private void jlReportesMenuBotonFacturasRealizadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonFacturasRealizadasMouseExited
        jlReportesMenuBotonFacturasRealizadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlReportesMenuBotonFacturasRealizadasMouseExited

    private void jlReportesMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuLogoutMouseClicked
        Login l15 = new Login();
        l15.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlReportesMenuLogoutMouseClicked

    private void jlReportesMenuBotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonMenuMouseClicked
        menuOpcionesAdmin moa5 = new menuOpcionesAdmin();
        moa5.setVisible(true);
        moa5.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
        this.setVisible(false);
    }//GEN-LAST:event_jlReportesMenuBotonMenuMouseClicked

    private void jlReportesMenuBotonUsuariosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonUsuariosRegistradosMouseClicked

        reportesVarios rv1 = new reportesVarios();
        try {
            String dir = System.getProperty("user.dir") + "\\src\\reportes\\repUsuariosSistema.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarrep = JasperFillManager.fillReport(reporteJasper, null, rv1.reporteConexion());
            JasperViewer.viewReport(mostrarrep, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jlReportesMenuBotonUsuariosRegistradosMouseClicked

    private void jlReportesMenuBotonCancionesVendidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonCancionesVendidasMouseClicked
        reportesVarios rv1 = new reportesVarios();
        try {
            String dir = System.getProperty("user.dir") + "\\src\\reportes\\repCantidadCanciones.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarrep = JasperFillManager.fillReport(reporteJasper, null, rv1.reporteConexion());
            JasperViewer.viewReport(mostrarrep, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jlReportesMenuBotonCancionesVendidasMouseClicked

    private void jlReportesMenuBotonFacturasRealizadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlReportesMenuBotonFacturasRealizadasMouseClicked
        reportesVarios rv1 = new reportesVarios();
        try {
            String dir = System.getProperty("user.dir") + "\\src\\reportes\\repFacturasRealizadas.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarrep = JasperFillManager.fillReport(reporteJasper, null, rv1.reporteConexion());
            JasperViewer.viewReport(mostrarrep, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jlReportesMenuBotonFacturasRealizadasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlCrearUsuario1;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario2;
    private javax.swing.JLabel jlCrearUsuario3;
    private javax.swing.JLabel jlCrearUsuario4;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlNextRegistro;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlReportesMenuBotonCancionesVendidas;
    private javax.swing.JLabel jlReportesMenuBotonFacturasRealizadas;
    private javax.swing.JLabel jlReportesMenuBotonMenu;
    private javax.swing.JLabel jlReportesMenuBotonUsuariosRegistrados;
    private javax.swing.JLabel jlReportesMenuExit;
    private javax.swing.JLabel jlReportesMenuLogout;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorLogin1;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    // End of variables declaration//GEN-END:variables
}
