/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.canciones;
import entidades.venta;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Formatter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import logicaNegocio.TextPrompt;
import logicaNegocio.cancionesVarios;
import logicaNegocio.ventaCanciones;
import org.codehaus.groovy.tools.shell.ParseCode;

/**
 *
 * @author obarboza
 */
public class ventas extends javax.swing.JFrame {

    /**
     * Creates new form ventas
     */
    public ventas() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt jtID = new TextPrompt("Identificacion del usuario", jtVentasSetId);
        TextPrompt JtNumeroFactura = new TextPrompt("Numero de factura", jtVentasGetNumeroFactura);
        TextPrompt jtFechaCompra = new TextPrompt("Fecha de la compra", jtVentasGetFecha);
        TextPrompt jtSubtotal = new TextPrompt("Subtotal de la compra", jtVentasGetSubTotal);
        TextPrompt jtTotal = new TextPrompt("Total de la compra", jtVentasGetTotal);
        consultaCanciones();
        cargaTabla();
        obtenerFechaActual();
        obtenerNumeroFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1MenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlNombreCompletoUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNextRegistro1 = new javax.swing.JLabel();
        jlCrearUsuario12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jseparadorLogin6 = new javax.swing.JSeparator();
        jseparadorCarrito = new javax.swing.JSeparator();
        jlCarrito = new javax.swing.JLabel();
        jlCarrito2 = new javax.swing.JLabel();
        jseparadorLogin9 = new javax.swing.JSeparator();
        jp2MenuRegistro = new javax.swing.JPanel();
        jlVentasExit = new javax.swing.JLabel();
        jseparadorLogin2 = new javax.swing.JSeparator();
        jlVentasLogout = new javax.swing.JLabel();
        jlVentasMenu = new javax.swing.JLabel();
        jseparadorLogin4 = new javax.swing.JSeparator();
        jlGeneroRegistro = new javax.swing.JLabel();
        jtVentasGetFecha = new javax.swing.JTextField();
        jlVentasBotonVerFactura = new javax.swing.JLabel();
        jtVentasGetSubTotal = new javax.swing.JTextField();
        jlGeneroRegistro1 = new javax.swing.JLabel();
        jlCrearUsuario6 = new javax.swing.JLabel();
        jlGeneroRegistro2 = new javax.swing.JLabel();
        jtVentasGetTotal = new javax.swing.JTextField();
        jtVentasSetId = new javax.swing.JTextField();
        jlGeneroRegistro3 = new javax.swing.JLabel();
        jtVentasGetNumeroFactura = new javax.swing.JTextField();
        jlGeneroRegistro4 = new javax.swing.JLabel();
        jseparadorLogin3 = new javax.swing.JSeparator();
        jlCrearUsuario8 = new javax.swing.JLabel();
        jlCrearUsuario9 = new javax.swing.JLabel();
        jlCrearUsuario10 = new javax.swing.JLabel();
        jlVentasBotonPagar = new javax.swing.JLabel();
        jlCrearUsuario11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVentaCanciones = new javax.swing.JTable();
        jlRemoverCancionCarrito = new javax.swing.JLabel();
        jlAgregarCancionCarrito = new javax.swing.JLabel();
        jlCrearUsuario5 = new javax.swing.JLabel();
        jlCrearUsuario13 = new javax.swing.JLabel();
        jseparadorLogin8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp1MenuRegistro.setBackground(new java.awt.Color(0, 0, 0));
        jp1MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_120.png"))); // NOI18N
        jp1MenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 130));

        jlNombreCompletoUsuario.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jlNombreCompletoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlNombreCompletoUsuario.setText("User");
        jp1MenuRegistro.add(jlNombreCompletoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_user.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jp1MenuRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jlNextRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-checkout-90.png"))); // NOI18N
        jp1MenuRegistro.add(jlNextRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, 80));

        jlCrearUsuario12.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario12.setText("Ventas");
        jp1MenuRegistro.add(jlCrearUsuario12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(new java.awt.Color(135, 211, 124));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(135, 211, 124));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable1);

        jp1MenuRegistro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 320, 300));

        jseparadorLogin6.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin6.setForeground(new java.awt.Color(51, 51, 51));
        jp1MenuRegistro.add(jseparadorLogin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 270, 10));

        jseparadorCarrito.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorCarrito.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorCarrito.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp1MenuRegistro.add(jseparadorCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 10, 90));

        jlCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-shopping-90.png"))); // NOI18N
        jp1MenuRegistro.add(jlCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, 80));

        jlCarrito2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlCarrito2.setForeground(new java.awt.Color(102, 102, 102));
        jlCarrito2.setText("Carrito");
        jp1MenuRegistro.add(jlCarrito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jseparadorLogin9.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin9.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp1MenuRegistro.add(jseparadorLogin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 10, 90));

        getContentPane().add(jp1MenuRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 730));

        jp2MenuRegistro.setBackground(new java.awt.Color(51, 51, 51));
        jp2MenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlVentasExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_exit.png"))); // NOI18N
        jlVentasExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlVentasExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlVentasExitMouseMoved(evt);
            }
        });
        jlVentasExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasExitMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlVentasExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jseparadorLogin2.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 4, 10, 24));

        jlVentasLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-login-rounded-30.png"))); // NOI18N
        jlVentasLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlVentasLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlVentasLogoutMouseMoved(evt);
            }
        });
        jlVentasLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasLogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasLogoutMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlVentasLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, -1));

        jlVentasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-menu-32.png"))); // NOI18N
        jlVentasMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlVentasMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlVentasMenuMouseMoved(evt);
            }
        });
        jlVentasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasMenuMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlVentasMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, -1));

        jseparadorLogin4.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin4.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 4, 10, 24));

        jlGeneroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-calendar-6-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 40, -1));

        jtVentasGetFecha.setEditable(false);
        jtVentasGetFecha.setBackground(new java.awt.Color(0, 0, 0));
        jtVentasGetFecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtVentasGetFecha.setForeground(new java.awt.Color(102, 102, 102));
        jtVentasGetFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtVentasGetFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 390, 30));

        jlVentasBotonVerFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-purchase-order-90.png"))); // NOI18N
        jlVentasBotonVerFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlVentasBotonVerFactura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlVentasBotonVerFacturaMouseMoved(evt);
            }
        });
        jlVentasBotonVerFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasBotonVerFacturaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasBotonVerFacturaMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlVentasBotonVerFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 80, 80));

        jtVentasGetSubTotal.setEditable(false);
        jtVentasGetSubTotal.setBackground(new java.awt.Color(0, 0, 0));
        jtVentasGetSubTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtVentasGetSubTotal.setForeground(new java.awt.Color(102, 102, 102));
        jtVentasGetSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtVentasGetSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 390, 30));

        jlGeneroRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-money-bag-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 40, -1));

        jlCrearUsuario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario6.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario6.setText("Menu");
        jp2MenuRegistro.add(jlCrearUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 29, -1, -1));

        jlGeneroRegistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-money-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 40, -1));

        jtVentasGetTotal.setEditable(false);
        jtVentasGetTotal.setBackground(new java.awt.Color(0, 0, 0));
        jtVentasGetTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtVentasGetTotal.setForeground(new java.awt.Color(102, 102, 102));
        jtVentasGetTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtVentasGetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 390, 30));

        jtVentasSetId.setEditable(false);
        jtVentasSetId.setBackground(new java.awt.Color(0, 0, 0));
        jtVentasSetId.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtVentasSetId.setForeground(new java.awt.Color(102, 102, 102));
        jtVentasSetId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtVentasSetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 390, 30));

        jlGeneroRegistro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons_ID.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 40, -1));

        jtVentasGetNumeroFactura.setEditable(false);
        jtVentasGetNumeroFactura.setBackground(new java.awt.Color(0, 0, 0));
        jtVentasGetNumeroFactura.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtVentasGetNumeroFactura.setForeground(new java.awt.Color(102, 102, 102));
        jtVentasGetNumeroFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jp2MenuRegistro.add(jtVentasGetNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 390, 30));

        jlGeneroRegistro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-hashtag-30.png"))); // NOI18N
        jp2MenuRegistro.add(jlGeneroRegistro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, -1));

        jseparadorLogin3.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin3.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 10, 50));

        jlCrearUsuario8.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario8.setText("Mostrar Factura");
        jp2MenuRegistro.add(jlCrearUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 700, -1, -1));

        jlCrearUsuario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario9.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario9.setText("Exit");
        jp2MenuRegistro.add(jlCrearUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 28, -1, -1));

        jlCrearUsuario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlCrearUsuario10.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario10.setText("Logout");
        jp2MenuRegistro.add(jlCrearUsuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 28, -1, -1));

        jlVentasBotonPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-money-bag-90.png"))); // NOI18N
        jlVentasBotonPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlVentasBotonPagar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlVentasBotonPagarMouseMoved(evt);
            }
        });
        jlVentasBotonPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVentasBotonPagarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlVentasBotonPagarMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlVentasBotonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, -1, 80));

        jlCrearUsuario11.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario11.setText("Pagar");
        jp2MenuRegistro.add(jlCrearUsuario11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 700, -1, -1));

        jtVentaCanciones.setBackground(new java.awt.Color(0, 0, 0));
        jtVentaCanciones.setForeground(new java.awt.Color(135, 211, 124));
        jtVentaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtVentaCanciones.setToolTipText("");
        jtVentaCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtVentaCanciones.setGridColor(new java.awt.Color(102, 102, 102));
        jtVentaCanciones.setSelectionBackground(new java.awt.Color(135, 211, 124));
        jtVentaCanciones.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jtVentaCanciones);

        jp2MenuRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 680, 260));

        jlRemoverCancionCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-minus-60.png"))); // NOI18N
        jlRemoverCancionCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRemoverCancionCarrito.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlRemoverCancionCarritoMouseMoved(evt);
            }
        });
        jlRemoverCancionCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRemoverCancionCarritoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlRemoverCancionCarritoMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlRemoverCancionCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 60, 50));

        jlAgregarCancionCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-add-new-60.png"))); // NOI18N
        jlAgregarCancionCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlAgregarCancionCarrito.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlAgregarCancionCarritoMouseMoved(evt);
            }
        });
        jlAgregarCancionCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAgregarCancionCarritoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlAgregarCancionCarritoMouseExited(evt);
            }
        });
        jp2MenuRegistro.add(jlAgregarCancionCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 60, 50));

        jlCrearUsuario5.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario5.setText("Remover Cancion");
        jp2MenuRegistro.add(jlCrearUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        jlCrearUsuario13.setForeground(new java.awt.Color(102, 102, 102));
        jlCrearUsuario13.setText("Agregar Cancion");
        jp2MenuRegistro.add(jlCrearUsuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jseparadorLogin8.setBackground(new java.awt.Color(102, 102, 102));
        jseparadorLogin8.setForeground(new java.awt.Color(51, 51, 51));
        jseparadorLogin8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jp2MenuRegistro.add(jseparadorLogin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 10, 60));

        getContentPane().add(jp2MenuRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 770, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String nombreUsr;
    String userId;
    String tipoUsr;
    String correoUsr;

    public void recibeDatos(String usr, String usr2, String tipoUsuario, String correoUsuario) {
        userId = usr2;
        nombreUsr = usr;
        tipoUsr = tipoUsuario;
        correoUsr = correoUsuario;
        jlNombreCompletoUsuario.setText(nombreUsr);
        jtVentasSetId.setText(userId);
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/logo_black_100.png"));

    public void obtenerFechaActual() {
        Date date = new Date();

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jtVentasGetFecha.setText(dateFormat.format(date));

    }

    public void consultaCanciones() {

        cancionesVarios cv = new cancionesVarios();

        ArrayList<canciones> canciones;

        canciones = cv.actualizarCancionesToCombo();

        if (canciones != null) {

            DefaultTableModel modelo = new DefaultTableModel();

            String[] nombresColumnas = {"Codigo Cancion", "Nombre Cancion", "Precio Cancion"};

            modelo.setColumnIdentifiers(nombresColumnas);

            Object[] columna = new Object[modelo.getColumnCount()];

            for (int i = 0; i < canciones.size(); i++) {

                columna[0] = canciones.get(i).getCodigoCancion();
                columna[1] = canciones.get(i).getNombreCancion();
                columna[2] = canciones.get(i).getPrecioCancion();

                modelo.addRow(columna);
            }

            jtVentaCanciones.setModel(modelo);

        }
    }

    public void cargaTabla() {
        String[] columnNames = {"Codigo Cancion", "Nombre Cancion", "Precio Cancion"};
        tablemodel.setColumnIdentifiers(columnNames);

        jTable1.setModel(tablemodel);
    }

    private void jlVentasExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasExitMouseClicked
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "Desea cerrar el programa?");

        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlVentasExitMouseClicked

    private void jlVentasExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasExitMouseMoved
        jlVentasExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlVentasExitMouseMoved

    private void jlVentasExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasExitMouseExited
        jlVentasExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlVentasExitMouseExited

    private void jlVentasLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasLogoutMouseMoved
        jlVentasLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlVentasLogoutMouseMoved

    private void jlVentasLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasLogoutMouseExited
        jlVentasLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlVentasLogoutMouseExited

    private void jlVentasMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMenuMouseMoved
        jlVentasMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlVentasMenuMouseMoved

    private void jlVentasMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMenuMouseExited
        jlVentasMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlVentasMenuMouseExited

    private void jlVentasBotonVerFacturaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonVerFacturaMouseMoved
        jlVentasBotonVerFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlVentasBotonVerFacturaMouseMoved

    private void jlVentasBotonVerFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonVerFacturaMouseExited
        jlVentasBotonVerFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlVentasBotonVerFacturaMouseExited

    private void jlVentasBotonVerFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonVerFacturaMouseClicked

        String numFactura;
        String idUsr;
        String fecha;
        String subTotalCompra;
        String totalCompra;
        String correo;

        numFactura = jtVentasGetNumeroFactura.getText();
        idUsr = jtVentasSetId.getText();
        fecha = jtVentasGetFecha.getText();
        subTotalCompra = jtVentasGetSubTotal.getText();
        totalCompra = jtVentasGetTotal.getText();
        correo = correoUsr;

        ArrayList<venta> listaVentas = new ArrayList();

        for (int i = 0; i < jTable1.getRowCount(); i++) {

            venta v1 = new venta();

            v1.setCodigoCancionFactura(jTable1.getValueAt(i, 0).toString());
            v1.setNombreCancionFactura(jTable1.getValueAt(i, 1).toString());
            v1.setPrecionCancionFactura(jTable1.getValueAt(i, 2).toString());

            listaVentas.add(v1);
        }
        factura f1 = new factura(nombreUsr, numFactura, idUsr, subTotalCompra, totalCompra, listaVentas, fecha, correo);
        f1.setVisible(true);

    }//GEN-LAST:event_jlVentasBotonVerFacturaMouseClicked

    private void jlVentasLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasLogoutMouseClicked
        Login l10 = new Login();
        l10.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlVentasLogoutMouseClicked

    private void jlVentasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasMenuMouseClicked
        if (tipoUsr.equals("Usuario")) {
            menuOpcionesUser mou = new menuOpcionesUser();
            mou.setVisible(true);
            this.setVisible(false);
            mou.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
            this.dispose();
        } else {
            menuOpcionesAdmin moa1 = new menuOpcionesAdmin();
            moa1.setVisible(true);
            this.setVisible(false);
            moa1.recibeDatos(nombreUsr, userId, tipoUsr, correoUsr);
            this.dispose();
        }

    }//GEN-LAST:event_jlVentasMenuMouseClicked

    private void jlVentasBotonPagarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonPagarMouseMoved
        jlVentasBotonPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlVentasBotonPagarMouseMoved
    int numeroFacturaVenta;

    public void obtenerNumeroFactura() {

        ventaCanciones vc1 = new ventaCanciones();

        ArrayList<venta> listaVentas;

        listaVentas = vc1.consultaCompraCabecera();
        
        for (int i = 0; i < listaVentas.size(); i++) {
            if (listaVentas.get(i).getNumeroFactura() == 0){
                numeroFacturaVenta++;
                jtVentasGetNumeroFactura.setText(String.valueOf(numeroFacturaVenta));
                break;
            }else{
                numeroFacturaVenta = listaVentas.get(i).getNumeroFactura();
                jtVentasGetNumeroFactura.setText(String.valueOf(numeroFacturaVenta));
                break;
            }
        }

    }

    private void jlVentasBotonPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonPagarMouseClicked

        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Por Favor Seleccione al menos una Cancion", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
        } else {
            venta v1 = new venta();
            ventaCanciones vc1 = new ventaCanciones();

            v1.setNumeroFactura(Integer.parseInt(jtVentasGetNumeroFactura.getText()));
            v1.setFecha(jtVentasGetFecha.getText());
            v1.setIdentificacionUsuario(jtVentasSetId.getText());
            v1.setTotalCompra(Double.parseDouble(jtVentasGetTotal.getText()));

            if (vc1.ingresocompraCabecera(v1) == true) {

                boolean compraExitosa = false;
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    v1.setNumeroFactura(Integer.parseInt(jtVentasGetNumeroFactura.getText()));
                    v1.setCodigoCancion(jTable1.getValueAt(i, 0).toString());
                    vc1.ingresocompraDetalle(v1);
                    compraExitosa = true;
                }

                if (compraExitosa) {
                    JOptionPane.showMessageDialog(null, "Compra realizada con exito", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                    jtVentasGetSubTotal.setText("");
                    jtVentasGetTotal.setText("");
                    tablemodel.setRowCount(0);
                    jtVentaCanciones.clearSelection();
                    obtenerNumeroFactura();
                    subTotal = 0;
                    total = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "Falló al completar la compra", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Falló al ingresar cabecera", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);

            }

        }
    }//GEN-LAST:event_jlVentasBotonPagarMouseClicked

    private void jlVentasBotonPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVentasBotonPagarMouseExited
        jlVentasBotonPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlVentasBotonPagarMouseExited

    private void jlAgregarCancionCarritoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarCancionCarritoMouseMoved
        jlAgregarCancionCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlAgregarCancionCarritoMouseMoved

    private void jlAgregarCancionCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarCancionCarritoMouseExited
        jlAgregarCancionCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlAgregarCancionCarritoMouseExited

    private void jlRemoverCancionCarritoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRemoverCancionCarritoMouseMoved
        jlRemoverCancionCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 211, 124)));
    }//GEN-LAST:event_jlRemoverCancionCarritoMouseMoved

    private void jlRemoverCancionCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRemoverCancionCarritoMouseExited
        jlRemoverCancionCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
    }//GEN-LAST:event_jlRemoverCancionCarritoMouseExited
    venta v2 = new venta();
    ArrayList<venta> cancion = new ArrayList<>();
    private DefaultTableModel tablemodel = new DefaultTableModel();

    double subTotal;
    double total;

    private void jlAgregarCancionCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgregarCancionCarritoMouseClicked
        boolean cancionAgregada = false;

        if (jtVentaCanciones.getSelectedRowCount() == 1) {

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 0).toString().equals(jTable1.getValueAt(i, 0).toString())) {
                    cancionAgregada = true;
                    break;
                } else {
                    cancionAgregada = false;
                }
            }
            if (jTable1.getRowCount() == 0) {
                jtVentasGetSubTotal.setText("");
                jtVentasGetTotal.setText("");

                String codigoCancion;
                String nombreCancion;
                String precioCancion;

                codigoCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 0).toString();
                nombreCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 1).toString();
                precioCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString();

                subTotal += Double.valueOf(jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString());
                //double valorConIva;
                //valorConIva = (subTotal * 0.10);
                //total = subTotal + valorConIva;
                total += Double.valueOf(jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString());

                jtVentasGetSubTotal.setText(Double.toString(subTotal));
                jtVentasGetTotal.setText(Double.toString(total));

                Object[] columna = new Object[tablemodel.getColumnCount()];

                columna[0] = codigoCancion;
                columna[1] = nombreCancion;
                columna[2] = precioCancion;

                tablemodel.addRow(columna);

                jTable1.setModel(tablemodel);
            } else {
                if (cancionAgregada == true) {
                    JOptionPane.showMessageDialog(null, "Cancion ya fue agregada al carrito de compras", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
                } else {
                    jtVentasGetSubTotal.setText("");
                    jtVentasGetTotal.setText("");

                    String codigoCancion;
                    String nombreCancion;
                    String precioCancion;

                    codigoCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 0).toString();
                    nombreCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 1).toString();
                    precioCancion = jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString();

                    subTotal += Double.valueOf(jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString());
                    //double valorConIva;
                    //valorConIva = (subTotal * 0.10);
                    //total = subTotal + valorConIva;
                    total += Double.valueOf(jtVentaCanciones.getValueAt(jtVentaCanciones.getSelectedRow(), 2).toString());

                    jtVentasGetSubTotal.setText(Double.toString(subTotal));
                    jtVentasGetTotal.setText(Double.toString(total));

                    Object[] columna = new Object[tablemodel.getColumnCount()];

                    columna[0] = codigoCancion;
                    columna[1] = nombreCancion;
                    columna[2] = precioCancion;

                    tablemodel.addRow(columna);

                    jTable1.setModel(tablemodel);

                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una unica fila", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
        }

    }//GEN-LAST:event_jlAgregarCancionCarritoMouseClicked


    private void jlRemoverCancionCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRemoverCancionCarritoMouseClicked

        if (jTable1.getSelectedRowCount() == 1) {
            subTotal -= Double.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            total -= Double.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jtVentasGetSubTotal.setText(Double.toString(subTotal));
            jtVentasGetTotal.setText(Double.toString(total));
            tablemodel.removeRow(jTable1.getSelectedRow());

        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "La tabla esta vacía", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una unica fila", "La Venta Musical", JOptionPane.INFORMATION_MESSAGE, m);
            }
        }
    }//GEN-LAST:event_jlRemoverCancionCarritoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlAgregarCancionCarrito;
    private javax.swing.JLabel jlCarrito;
    private javax.swing.JLabel jlCarrito2;
    private javax.swing.JLabel jlCrearUsuario10;
    private javax.swing.JLabel jlCrearUsuario11;
    private javax.swing.JLabel jlCrearUsuario12;
    private javax.swing.JLabel jlCrearUsuario13;
    private javax.swing.JLabel jlCrearUsuario5;
    private javax.swing.JLabel jlCrearUsuario6;
    private javax.swing.JLabel jlCrearUsuario8;
    private javax.swing.JLabel jlCrearUsuario9;
    private javax.swing.JLabel jlGeneroRegistro;
    private javax.swing.JLabel jlGeneroRegistro1;
    private javax.swing.JLabel jlGeneroRegistro2;
    private javax.swing.JLabel jlGeneroRegistro3;
    private javax.swing.JLabel jlGeneroRegistro4;
    private javax.swing.JLabel jlNextRegistro1;
    private javax.swing.JLabel jlNombreCompletoUsuario;
    private javax.swing.JLabel jlRemoverCancionCarrito;
    private javax.swing.JLabel jlVentasBotonPagar;
    private javax.swing.JLabel jlVentasBotonVerFactura;
    private javax.swing.JLabel jlVentasExit;
    private javax.swing.JLabel jlVentasLogout;
    private javax.swing.JLabel jlVentasMenu;
    private javax.swing.JPanel jp1MenuRegistro;
    private javax.swing.JPanel jp2MenuRegistro;
    private javax.swing.JSeparator jseparadorCarrito;
    private javax.swing.JSeparator jseparadorLogin2;
    private javax.swing.JSeparator jseparadorLogin3;
    private javax.swing.JSeparator jseparadorLogin4;
    private javax.swing.JSeparator jseparadorLogin6;
    private javax.swing.JSeparator jseparadorLogin8;
    private javax.swing.JSeparator jseparadorLogin9;
    private javax.swing.JTable jtVentaCanciones;
    private javax.swing.JTextField jtVentasGetFecha;
    private javax.swing.JTextField jtVentasGetNumeroFactura;
    private javax.swing.JTextField jtVentasGetSubTotal;
    private javax.swing.JTextField jtVentasGetTotal;
    private javax.swing.JTextField jtVentasSetId;
    // End of variables declaration//GEN-END:variables
}
